### ISSUE TITLE
Limit the number of times "Maximum Window" error message is called.

### ISSUE THREAD

**Issue by afraj-attar** [iTwin/appui#1047]
### Is your feature request related to a problem? Please describe.

In the iTwin viewer, when we zoom all the way out we receive a repeated on-screen message (Toast message) with error 'Maximum window'. This spams the screen with the error message.

![image](https://github.com/user-attachments/assets/560a06da-fc06-475e-b44c-d000fee3d799)

### Describe the Solution you'd like

When a user zooms all the way out we should show the error message "Maximum window" only once.

**Comment by GerardasB** [comment]
Fixed by #1042
