### ISSUE TITLE
Toast message prevents user from clicking on content of status bar popover

### ISSUE THREAD

**Issue by AnDuong249** [iTwin/appui#1076]
### Describe the bug

The toast message created from the MessageManager is blocking the content of status bar popover if the status bar popover is too close to the toast

### To Reproduce

1. Open Design Review app - contact me for direct link.
2. Turn on display optimizations if not enabled
3. A toast message regarding 3d tile optimization should pop up.
4. Click on the diagnostic tools icon on the status bar (briefcase icon)
5. Notice that you can only click on the label of the checkbox. If the checkbox is clicked, the popover would close. 

### Expected Behavior

The toast message would not block the content of the status bar popover unless it's directly underneath the toast.

### Screenshots

![Image](https://github.com/user-attachments/assets/8d0ad03c-a9ce-4972-8daa-4210122f3cd4)
![Image](https://github.com/user-attachments/assets/3d9e09ff-87fd-4b92-8b0e-568f448b9998)

Notice how the toast is covering the checkbox in this screenshot.
![Image](https://github.com/user-attachments/assets/6cc00aa3-fe26-4f35-8009-6ee682ed6ff2)

### Desktop (please complete the applicable information)

- iTwin.js 4.9.3
- AppUI 4.17.1
- iTwinUI 3.15.1/2.12.26 (both has the same bug)

**Comment by GerardasB** [comment]
Fixed by https://github.com/iTwin/iTwinUI/pull/2323
