### ISSUE TITLE
ToolbarGroupItem not accepting output of UiItemsProvider.getToolbarItems()

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/appui#1112]
### Describe the bug

Hey,
I’m working on integrating our latest civil packages using the newer `UiItemsProvider` interfaces within pineapple.

What I'm trying to do is collect the output of multiple `UiItemsProvider.getToolbarItems()` and return that under a single group item (snippet below).
The compiler is yelling at me because what `getToolbarItems()` return is `ToolbarItem[]` (which includes `ToolbarCustomItem`), and the `ToolbarGroupItem` I’m trying to create only accepts `ToolbarActionItem | ToolbarGroupItem`.

I was wondering if this is just an oversight, or it's by design? It seems to make composition a bit harder than it should be.
I can use the `isToolbarCustomItem` and filter those out entirely, but I wanted to ask first. In this case, I'm the author of both the UiItemsProvider and the code that consumes it, so I know there is no custom item...

Snippet of code:
```ts
  public getToolbarItems(): ToolbarItem[] {
    let items: ToolbarItem[] = [];

    for (const provider of this.providers) {
      items = items.concat(provider.getToolbarItems());
    }
    return [ToolbarItemUtilities.createGroupItem({
      id: "my-complex-group-item",
      items,
      label: "Composition provider test",
      layouts: {
        standard: {
          orientation: ToolbarOrientation.Vertical,
          usage: ToolbarUsage.ContentManipulation,
        },
      },
    })];
  }
```

Thanks!
Alex

**Comment by GerardasB** [comment]
`ToolbarGroupItem` API was intentionally designed to disallow custom items (this was related to challenges in old/outdated designs) - that's why group items can only contain other group or action items. I think we could revisit this with our new toolbar implementation, but that would fall under new feature request instead.
Your approach of filtering the custom items out seems correct to me.
