### ISSUE TITLE
Make useRefState public

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/appui#1122]
### Is your feature request related to a problem? Please describe.

We are using `useRefState`. Could it be made public?

Maybe [@itwin/react-hooks](https://github.com/iTwin/react-hooks) would be a better home for it?

**Comment by GerardasB** [comment]
I'd prefer to keep this hook private to AppUI packages. It's literally a 4 liner, you can simply copy it to your code-base or add it to `@itwin/react-hooks` package.
