### ISSUE TITLE
AppUI 4.0 Overview

### ISSUE THREAD

**Issue by calebmshafer** [iTwin/appui#117]
> Note: this issue is a high level overview of the goal of the 4.0 release for posterity and clarity when communicating it.

The AppUI 4.0 major release is a shift in how we will handle developing and delivering AppUI moving forward. As the new repo suggests, AppUI will be broken out of the fixed version policy that the rest of the iTwin.js core packages follow and instead follow it's own release cycle moving forward. (it will still be subject to the API policies that the rest of iTwin.js will follow starting with 4.0).

In addition to 

- **Removal of the "UI 1.0" code**.  After many years in a deprecated state, we will be completely removing the support for what was called UI 1.0 or 9Zone and shifting to completely focus on the new AppUI (aka "UI 2.0") implementation and design.
-  **Adoption of iTwinUI 2.0**.  With the new major version of iTwinUI being released, AppUI will be adopting it and all the features it adds. This update gives us an opportunity to re-evaluate how AppUI interacts with iTwinUI and leverage it in a more maintainable way moving forward.

   This includes:
   - Dropping any duplicate components between AppUI and iTwinUI
   - Remove duplication of css and scss variables that are available as part of iTwinUI
- **Re-defining AppUI Abstract**.

    The `@itwin/appui-abstract` package has been the link between UI concepts in a non-React way required from a `core-frontend` perspective to support Tools, Tool Settings, Dialogs and a few other piecesof UI. However, over time more and more AppUI design system concepts have been added to the abstract package making it unclear where the line should be drawn.  With this release, we are starting the journey of cleaning that up by removing some concepts that are explicitly AppUI (e.g. the FrontStage and BackStage concept). This major release is the first step in that direction and will be continue to be defined as we move forward with AppUI.

**Comment by raplemie** [comment]
AppUI 4.0.0 was released today, May 1st 2023!
