### ISSUE TITLE
react to Node 18.13 ICU 72 Version Breaking Change Date/Time format

### ISSUE THREAD

**Issue by aruniverse** [iTwin/appui#125]
> @raplemie @GerardasB @NancyMcCallB looks like there are a couple issues with the CI now that I switched it to the latest Node 18 version. Can you take a look?
> 
> ```
> --[ FAILURE: @itwin/components-react ]--------------[ 1 minute 20.2 seconds ]--
> 
> undefined
> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactDataGrid, Viewport, t
> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
> 
>   ...285 lines omitted...
>       at waitForWrapper (D:\vsts_a\4\s\common\temp\node_modules\.pnpm\@testing-library+dom@8.20.0\node_modules\@testing-library\dom\dist\wait-for.js:166:27)
>       at Context.<anonymous> (src\test\editors\DateTimeEditor.test.tsx:257:25)
>       at processImmediate (node:internal/timers:471:21)
> 
> 
> 
> ERROR: Coverage for lines (99.89%) does not meet global threshold (100%)
> ERROR: Coverage for functions (99.89%) does not meet global threshold (100%)
> ERROR: Coverage for branches (99.93%) does not meet global threshold (100%)
> ERROR: Coverage for statements (99.9%) does not meet global threshold (100%)
> 
> --[ FAILURE: @itwin/imodel-components-react ]--------[ 1 minute 7.2 seconds ]--
> 
> 
>   288 passing (30s)
>   1 failing
> 
>   1) <TimelineComponent showDuration={true} />
>        should respect time zone offset:
> 
>       AssertionError: expected '07:00:00\u202fPM' to equal '07:00:00 PM'
>       + expected - actual
> 
>       -07:00:00 PM
>       +07:00:00 PM
>       
>       at Context.<anonymous> (src\test\timeline\TimelineComponent.test.tsx:889:41)
>       at processImmediate (node:internal/timers:471:21)
> ```

https://github.com/nodejs/node/issues/46123

_Originally posted by @aruniverse in https://github.com/iTwin/itwinjs-core/issues/4995#issuecomment-1409227528_

**Comment by raplemie** [comment]
Test have been updated to account for this in #143
