### ISSUE TITLE
Build and test using react 17 and react 18

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#159]
Potentially using rush --variant's and some codemod, we should build in both React17 and React18 the tests and applications to validate that we are not breaking in either versions.

Potential tasks:
- [ ] Figure a way to update `import` statement between the different versions of `react-testing-library` (latest includes `renderHook`)
- [ ] Ensure `rush build --variant react18` would actually work as expected.
- [ ] Include in CI

Followup of #97

**Comment by GerardasB** [comment]
With AppUI 5.0 we plan to support the latest React version, closing for now.
