### ISSUE TITLE
canPopout: if frontstage is switched while popout is open, it does not return to original position

### ISSUE THREAD

**Issue by cfranklyn** [iTwin/appui#202]
**Describe the bug**
If a widget is popped out into a separate browser window. That window must be closed before the frontstage is closed in order for it to retain it's original position.

**To Reproduce**

1. Set the "canPopout" property of a widget in a frontstage.
2. Select the frontstage, Set the widget in a docked position at the bottom of the window
3. Pop out the widget into a separate window.
4. **Without closing the separate window** switch to a different frontstage
5. Switch back to frontstage with popout widget.
6. Widget appears floating in a tiny window in the main view.

**Expected behavior**
Widget should return to the docked position in this instance rather than defaulting to a floating position.

**Screenshots**
Widget is docked, popout window is pressed
![image](https://user-images.githubusercontent.com/92109722/224841728-792c2c29-8d30-4642-b304-00cea8893eab.png)

Frontstage is switched, then switched back, widget is not docked:
![image](https://user-images.githubusercontent.com/92109722/224841924-742ebf64-75c9-4bb2-9e22-56d4065e9ace.png)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- Version: 110.0.5481.180 (Official Build) (64-bit)
- iTwin.js Version: 3.6.0

**Comment by raplemie** [comment]
Hi @cfranklyn, a fix for this was released in 4.8.0, let us know if this fixes your issue!
