### ISSUE TITLE
Allow using a react component as an icon for Widgets when writing UiItemsProvider

### ISSUE THREAD

**Issue by aruniverse** [iTwin/appui#210]
AbstractWidgetProps icon should probably allow for an HTML element as well. Right now you're stuck using the webfont icons or suing the Icon utilities to create an IconSpec from the svg?sprite or web components.

For Toolbar items we've been creating CustomItemDefs, which allow for a ReactNode as the iconSpec. 
Clearly we can't use React.ReactNode in appui-abstract but should allow for some type of HTML element, or provide a helper like we do for CustomItemDefs

This request is being driven by DR

Here is how we currently use iconSpecs for toolbar items: https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/geo-tools/src/GeoToolsItemDef.tsx#L24

**Comment by GerardasB** [comment]
`icon` property of a widget is now of `IconSpec` type, allowing `ReactNode` to be provided as an icon.
