### ISSUE TITLE
Review `byRole` tests using "title" as the name, will break with testing-library updates

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#227]
@GerardasB @raplemie Any idea what to do about the [test failures](https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=2035454&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=429853d2-592c-5f99-537b-6a3154c944ed&l=4545)?

As best I can tell, it looks like a (semver-compatible) update to @testing-library/dom or one of its dependencies has broken the behavior of `getByRole` in that the `title` attribute is no longer being considered when determining the accessible name.  I'm not sure how relevant this is, but [this issue](https://github.com/A11yance/aria-query/issues/379#issuecomment-1227863154) on GitHub seems to suggest this may be intentional...

Tests are failing at:

https://github.com/iTwin/appui/blob/627e041687eac6787810a2c8be3d2cfb14f0106a/ui/components-react/src/test/properties/renderers/value/ArrayPropertyValueRenderer.test.tsx#L60
https://github.com/iTwin/appui/blob/627e041687eac6787810a2c8be3d2cfb14f0106a/ui/components-react/src/test/properties/renderers/value/StructPropertyValueRenderer.test.tsx#L49
https://github.com/iTwin/appui/blob/627e041687eac6787810a2c8be3d2cfb14f0106a/ui/core-react/src/test/button/UnderlinedButton.test.tsx#L30

_Originally posted by @wgoehrig in https://github.com/iTwin/appui/issues/216#issuecomment-1481234364_

**Comment by GerardasB** [comment]
TBD if that's still an issue when updating the RTL version.
