### ISSUE TITLE
canPopout: Issue with (iTwin-React) Dialogs

### ISSUE THREAD

**Issue by cfranklyn** [iTwin/appui#236]
**Describe the bug**
I am not able to move and resize iTwin-React dialogs (have not tried other dialog types) when my widget is popped out.
When I click the title bar to move, or the edges to resize, the dialog becomes "stuck" to my cursor (in other words, if I mouseDown
to resize or move the dialog, when I mouseUp, the dialog is stuck to the cursor). 

This only happens when a widget is popped out to another window.

**To Reproduce**

1. Set canPopout widget property to "true" and pop out the widget
2. Open a Dialog (with "isDraggable" and "isResizeable" set to true)
3. Attempt to move the dialog or resize it 
4. The Dialog is stuck to the mouse cursor

**Expected behavior**
After the user is done resizing or moving, they let go of the mouse button, the Dialog should no longer be moved or resized.

**Screenshots**
![image](https://user-images.githubusercontent.com/92109722/228642495-d13f2242-54f9-4903-8938-cc58ec3bd363.png)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- Version  111.0.5563.146 (Official Build) (64-bit)
- iTwin.js AppUI Version [3.6.1]

**Additional context**

**Comment by raplemie** [comment]
@mayank99, @gretanausedaite This seems related to this line in the resizer, the `addEventListener` is correctly called on the `ownerDocument` but is `removeEventListener` is called on `document`:

https://github.com/iTwin/iTwinUI/blob/651f29dd99417eef44edcb51cd130e1fd003b769/packages/itwinui-react/src/core/utils/components/Resizer.tsx#L192

**Comment by mayank99** [comment]
I've created a PR https://github.com/iTwin/iTwinUI/pull/1174

**Comment by mayank99** [comment]
This is now fixed and released in [`@itwin/itwinui-react@2.8.0`](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.8.0)
