### ISSUE TITLE
ResizeObserver error thrown when ButtonGroup is used in Widget

### ISSUE THREAD

**Issue by saskliutas** [iTwin/appui#240]
**Describe the bug**
`ResizeObserver loop limit exceeded` error is thrown when ButtonGroup component from `@itwin/itwinui-react` package is used in Widget.

**To Reproduce**

1. Clone https://github.com/saskliutas/itwin-viewer-app
2. Setup .env file using instructions in README file
3. Launch app
4. Click `Collapse` button from Widget in right panel

**Expected behavior**
Error should not be thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/24278440/229140303-4e988e63-db98-41e3-bffa-159121048927.png)
![image](https://user-images.githubusercontent.com/24278440/229140444-8862b19f-4a31-4738-9296-62af8a3a97f1.png)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Edge, FireFox
- iTwin.js AppUI Version: 3.7.0. (same in 3.5.5)
- iTwin.js Version: 3.7.0 (same in 3.5.5

**Additional context**
Tried to reproduce same error in fresh react app created with `vite` and `create-react-app` using only `@itwin/itwinui-react`. Also tried to reproduce this in `iTwin.js sandbox` and `codesandbox.io`. It looks like this error is only thrown in development mode and only when ButtonGroup is used in appui Widget.

**Comment by raplemie** [comment]
Hi, OP issue can actually be recreated by using your provided "MyComponent" in a create-react-app but only when using React17 (rather than the default React18, which work fine) I'll follow up with iTwinUI teams and get back to you, we may transfer the issue there.

**Comment by raplemie** [comment]
Created itwin/itwinui#1317, will close this one. @a-gagnon Please create a different issue if its unrelated to iTwinUI components.
