### ISSUE TITLE
Calling `MessageManager.displayMessage` with `reactNode` throws an error

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#276]
**Describe the bug**
`MessageManager.displayMessage` throws an error when `reactNode` is specified as a message.

**To reproduce**

Call `MessageManager.displayMessage` with `reactNode` as a message.
```
const reactNode = <div>Test</div>;
const message = new ReactNotifyMessageDetails(OutputMessagePriority.Info, { reactNode }, undefined, OutputMessageType.Sticky);
const displayedMessage = MessageManager.displayMessage(message);
```

**Current behavior**
Error is thrown:
`Objects are not valid as a React child (found: object with keys {reactNode}). If you meant to render a collection of children, use an array instead.`

**Expected behavior**
Message is displayed as a toast.

**Comment by raplemie** [comment]
This should be fixed by #280 it was a missed port of a fix we had in 3.6
