### ISSUE TITLE
No spacing between tree node's checkbox and label

### ISSUE THREAD

**Issue by grigasp** [iTwin/appui#277]
**Describe the bug**
There's no margin between node checkbox and label

**To Reproduce**

1. Go to https://www.itwinjs.org/sandboxes/grigas/ControlledTree
2. Have a look at the tree node
  ![image](https://user-images.githubusercontent.com/35135765/232678373-666a9ee5-0ee0-478b-9746-6854568b2c97.png)

**Expected behavior**
There should be some margin between the checkbox and the label.

**Desktop (please complete the applicable information):**

- OS: Windows 10
- Browser: Chrome
- Version 112.0.5615.86 (Official Build) (64-bit)
- iTwin.js AppUI Version 3.5.5
- iTwin.js Version 3.5.5

**Additional context**

Most likely introduced when switching from `core-react` checkbox component to `itwinui-react` checkbox component in this PR: https://github.com/iTwin/itwinjs-core/pull/1252.

**Comment by GerardasB** [comment]
This needs to be backported to 3.7 as well.
