### ISSUE TITLE
Populate AppUI with tool registry

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#292]
**Is your feature request related to a problem? Please describe.**
UiItemsProvider are currently used to register toolbars, but that is now part of appui-react and will not allow extensions to register without requiring appui-react.

**Describe the solution you'd like**
The tools already need to be registered in the `ToolRegistry`, it would be good to have to handle that only once, there.

**Describe alternatives you've considered**

**Additional context**
The goal of this issue is to start discussion on what should be done here.

**Comment by GerardasB** [comment]
Seems like consumers can already do that by iterating the registered tool and utilizing [ToolbarItemUtilities.createForTool](https://www.itwinjs.org/reference/appui-react/toolbar/toolbaritemutilities/toolbaritemutilities.createfortool/)
