### ISSUE TITLE
ToolAssistanceField does not render icon for instruction 'Identify Element'

### ISSUE THREAD

**Issue by jason-crow** [iTwin/appui#303]
**Describe the bug**
The ToolAssistanceField status bar popup does not render an icon for the 'Identify Element' instruction

**To Reproduce**

1. Have Select tool active
2. Click on ToolAssistanceField in the status bar to open its dialog
3. Notice the cursor Icon is missing

**Expected behavior**
![image](https://user-images.githubusercontent.com/25822334/235142027-886b6b91-5b25-48d5-bdb9-d11eb813303a.png)
**Current behavior**
![image](https://user-images.githubusercontent.com/25822334/235142123-82318d7e-fbb9-4fe2-9164-50d0629b62f1.png)

**Desktop (please complete the applicable information):**

- OS: windows
- Browser chrome
- Version  112.0.5615.138
- iTwin.js AppUI Version 4.0.0-dev.20
- iTwin.js Version 3.7.0

**Additional context**
The `nz-image` span contains no `<i class="icon icon-cursor" />` like it does in 3.7, I suspect it's missing because of this  code
![image](https://user-images.githubusercontent.com/25822334/235141914-f47ee7de-d919-46cb-af8c-ab7151a3a847.png)

Here's our defect: https://dev.azure.com/bentleycs/beconnect/_workitems/edit/1181017

**Comment by wilmaier** [comment]
Well it looks like all tools that use tools assistance:
![image](https://github.com/iTwin/appui/assets/48260215/743bc73e-eab4-47e9-812a-9120c502f6d8)

**Comment by raplemie** [comment]
Hi, I see the change that caused this issue, indeed, every tool that uses webfont will have this issue, I'll look into fixing it.

**Comment by raplemie** [comment]
Hi, the fix for this was released minutes ago in 4.0.1.
