### ISSUE TITLE
SnapMode icons loads a split second later than the labels on widget open

### ISSUE THREAD

**Issue by AnDuong249** [iTwin/appui#308]
**Describe the bug**
When expanding the SnapMode widget, the icons loads a split second later than the labels on widget open

**To Reproduce**

1. In status bar, expand snap mode widget.
2. Notice that on widget open, snap mode icons just loads a split second later, causing sort of a refresh effect.

**Expected behavior**
Both the icons and labels to load at the same time. It used to look like this.
![Recording 2023-05-02 at 13 41 29](https://user-images.githubusercontent.com/116378951/235781377-efd9b9b0-a2c1-42df-abbe-0563b8155c38.gif)

**Screenshots**
Here's how the current bug is looking like
![Recording 2023-05-02 at 13 43 48 (1)](https://user-images.githubusercontent.com/116378951/235781594-9afb5517-4555-44db-bb23-7cc0f4d9e4ae.gif)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- Version  112.0.5615.138
- iTwin.js AppUI Version 4.0.0-dev-20
- iTwin.js Version 3.7.0

**Additional context**
Here's our defect: https://dev.azure.com/bentleycs/beconnect/_workitems/edit/1181071

**Comment by raplemie** [comment]
Hi, this is due to a change of icon type introduced earlier (webSvg vs webFont). We'll investigate what can be done to reduce/remove this delay effect.

**Comment by raplemie** [comment]
Hi, this has been modified to remove the multiple reloading of the SVG on subsequent display and released in 4.2.0, let us know if this adress your issue!
