### ISSUE TITLE
Selection Count showing inconsistent results with 3.7.x version

### ISSUE THREAD

**Issue by jason-crow** [iTwin/appui#313]
The selected elements count that the `SelectionInfoField` in the status bar shows can shows results that are inconsistent with the value that was shown in 3.7.x.. Specifically, this is due to the separation of the Presentation code which previously would for example show a single selected element for assembly scope picks, which now will count all the individual elements included in that assembly.

The 3.7.x handling of this is as follows (found [here](https://github.com/iTwin/itwinjs-core/blob/a242c44b86d6c9f8e4615997d5ed6815f88024bd/ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts#L272)):
```typescript
SyncUiEventDispatcher._unregisterListenerFunc = Presentation.selection.selectionChange.addListener((args: SelectionChangeEventArgs, provider: ISelectionProvider) => {
      // istanbul ignore if
      if (args.level !== 0) {
        // don't need to handle sub-selections
        return;
      }
      const selection = provider.getSelection(args.imodel, args.level);
      const numSelected = getInstancesCount(selection);
      UiFramework.dispatchActionToStore(SessionStateActionId.SetNumItemsSelected, numSelected);
    });
```
In 4.x since no Presentation source can be used it now does (found [here](https://github.com/iTwin/appui/blob/2bd008c84e5f297ddfea2f54e4909606dbbbaa6b/ui/appui-react/src/appui-react/syncui/SyncUiEventDispatcher.ts#L228)):
```typescript
SyncUiEventDispatcher._unregisterListenerFunc = iModelConnection.selectionSet.onChanged.addListener((ev) => {
      const numSelected = ev.set.elements.size;
      UiFramework.dispatchActionToStore(SessionStateActionId.SetNumItemsSelected, numSelected);
    });
```
I think the handling of using the `IModelConnection.selectionSet.onChanged` is a decent default, but for instance, if you use a viewport component wrapped by the presentation's `WithUnifiedSelection` then the individual elements of an assembly selection will trigger that onChanged event [here](https://github.com/iTwin/presentation/blob/cda02054a2bada96fb66d3d26aac68b1ba2bcf4b/packages/components/src/presentation-components/viewport/WithUnifiedSelection.tsx#L154) causing the count to show that instead of 1 even if from the user's persective they only selected 1 element (also the behavior consistent with 3.7.x).

**To Reproduce**

1. Go to https://qa-review-uks.itwin.bentley.com/context/8b3d0653-02b5-4a76-832e-7c16ed50ff21/imodel/b9bf7a2d-bf2e-4d3f-b127-90c8029a855e?it3Mode
2. Select the 'assembly' scope
3. click on a window pane
4. notice the selection info in the status bar shows 6 selements selected

**Expected behavior**
Only 1 element is selected (this was the behavior from 3.7.x)

**Screenshots**
![image](https://github.com/iTwin/appui/assets/25822334/1571c195-6a9a-4e11-b6e9-61f8d18c2499)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- iTwin.js AppUI Version: 4.0.0
- iTwin.js Version: 3.7.0

**Additional context**
Again it's probably as good of a default as you can do without having a Presentation dependency, but since this when used with Presentation will cause unexpected results, I think it would be ideal if we could easily opt out of having AppUi setup that listener on the `iModelConnection.selectedSet.onChanged` that dispatches to the count for `SessionStateActionId.SertNumItemsSelected`. This would allow us to recreate the same handling to dispatch that as was done in 3.7.x (code snippet shown above). This would be ideal for us since we could continue using the `SelectionInfoField`. Also there may be further complication if other features rely on that same redux state that this solution would also solve.

Here is our defect for this: [Selection count shows multiple elements as selected even though only one was](https://dev.azure.com/bentleycs/beconnect/_workitems/edit/1193046)

**Comment by jason-crow** [comment]
@grigasp @raplemie

**Comment by GerardasB** [comment]
@jason-crow I'd prefer to add a separate presentational component (styling only, accepts a selection count as a prop) instead. Would that work in your case?

**Comment by jason-crow** [comment]
@GerardasB yes that works. Should I create a issue for presentation and close this one?

**Comment by GerardasB** [comment]
> @GerardasB yes that works. Should I create a issue for presentation and close this one?

@jason-crow, I've opened a PR to address this from the AppUI side: https://github.com/iTwin/appui/pull/323
It depends on the presentation maintainers if they want to provide something like a `useSelectionCount` hook for easier composition.
