### ISSUE TITLE
ConditionalIconItem a valid type for IconSpec, but not working?

### ISSUE THREAD

**Issue by jason-crow** [iTwin/appui#315]
The [IconSpec](https://github.com/iTwin/appui/blob/7284cd95619addb7fce98abf3d3ee060fa42c2ba/ui/core-react/src/core-react/icons/IconComponent.tsx#L21) type lists [ConditionalIconItem](https://github.com/iTwin/appui/blob/master/ui/core-react/src/core-react/icons/ConditionalIconItem.tsx) as a valid type, but it doesn't appear to be functional for something like a [ToolItemDef](https://github.com/iTwin/appui/blob/master/ui/appui-react/src/appui-react/shared/ToolItemDef.ts) which has an `icon` field that is typed as `IconSpec`

**To Reproduce**
1. Create a ToolItemDef instance for a ToolbarComposer that is set with an icon defined as a `ConditionalIconItem`
2. Notice the icon in the app shows as blank

**Expected behavior**
Expected this to behave exactly like `ConditionalStringValue` except I could use a React.Node for the actual icon, which is the primary use case for attempting to use `ConditionalIconItem` instead

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- Version: 112.0.5615.138
- iTwin.js AppUI Version: 4.0.0
- iTwin.js Version: 3.7.0

**Additional context**
I was expecting to find handling for this in [ToolbarItemsManager](https://github.com/iTwin/appui/blob/7284cd95619addb7fce98abf3d3ee060fa42c2ba/ui/appui-react/src/appui-react/toolbar/ToolbarItemsManager.ts#L156) where it checks the `ConditionalStringValue` and `ConditionalBooleanValue`

**Comment by raplemie** [comment]
Hi! A fix for this have been included and released in 4.2.0, let us know if it addresses your isssue !
