### ISSUE TITLE
Remove inline styling from AppUI packages

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/appui#318]
Use a strict CSP as our main method for mitigating XSS attacks. Part of this is [prevention of inline styles](https://web.dev/csp/#inline-code-is-considered-harmful)
Content security policyContent Security Policy can significantly reduce the risk and impact of cross-site scripting attacks in modern browsers.

**Comment by raplemie** [comment]
@kckst8 Can you provide which part is causing problem with the rule ? React should already handle correctly the style props by assigning them directly according to https://github.com/facebook/react/issues/5878#issuecomment-172964266, so I suppose it is not what is causing issues (like resizing a panel or moving a floating widget around)

**Comment by raplemie** [comment]
After internal discussions with @kckst8, there is not current issue direclty with AppUI packages infringing no-style CSP, so I'll close this and we can create other issues if specific components turns out to be problematic.
