### ISSUE TITLE
Inconsistent SCSS File Formatting

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#331]
**Describe the bug**

The SCSS file formatting in our project is inconsistent, leading to difficulties in maintaining a clean and organized codebase. Furthermore, this is adding additional overhead when reviewing PRs with formatting-only changes.

There seems to be inadequate space around selectors, making the code less readable.
Currently, there are **83** search hits for `>.` and **215** search hits for `> .` in `*.scss` files.

**Expected behavior**

SCSS files are well-formatted and consistent.

**Comment by FlyersPh9** [comment]
What is the reasoning for `devDependencies` being set in each package rather than in the root? https://github.com/iTwin/appui/blob/cdf196a5ab3abe1fc6b00f26094639d11df1ca71/package.json#LL33C9-L33C9

**Comment by raplemie** [comment]
As this is a rush monorepo, the root package is not expected to be a real package with dependency but simply there for warnings. Plus the packages `should` be autonomus (so you "should" be able to bring the package and test them without having the full monorepo setup, that likely not work though, but that's part of the idea.)
