### ISSUE TITLE
Explore distancing from core

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#333]
We would like to reduce the dependencies on iTwin.js core packages to facilitate the user of the packages in other environments (like codesandbox)
We need to validate what is currently tying us to core, what would be the required changes, and if it would be worth making the effort to do it.

**Comment by raplemie** [comment]
Currently looking where all the dependencies are to core packages (Will be working on this part time only)

**Comment by GerardasB** [comment]
The end goal is to:
- Get rid of imperative initialization
- Get rid of static classes
- Get rid of iTwin.js dependencies in all packages except `@itwin/imodel-components-react`

**Comment by GerardasB** [comment]
This seems like a general direction we want to go to, let's identify exact steps and file specific issues. Created a milestone as well https://github.com/iTwin/appui/milestone/4
