### ISSUE TITLE
VirtualizedPropertyGrid: Action buttons might overflow

### ISSUE THREAD

**Issue by saskliutas** [iTwin/appui#336]
**Describe the bug**
ActionButtons in `VirtualizedPropertyGrid` might overflows at small size.

**To Reproduce**

1. Place `VirtualizedPropertyGrid` with some actions buttons into resizable panel.
2. Start reducing panel width.
3. Actions buttons start overflowing `VirtualizedPropertyGrid`

**Expected behavior**
Actions buttons should stay inside.

**Screenshots**
![image](https://github.com/iTwin/appui/assets/24278440/44e942e8-406b-4a3b-af6a-75a769739cfa)

**Additional context**
If width is reduced even more `VirtualizedPropertyGrid` item style changes and buttons do not overflow. https://github.com/iTwin/appui/blob/cdf196a5ab3abe1fc6b00f26094639d11df1ca71/ui/components-react/src/components-react/properties/renderers/PropertyGridColumns.ts#L76

**Comment by raplemie** [comment]
Fix available in 4.2.0.
