### ISSUE TITLE
AppUI doesn't have close button

### ISSUE THREAD

**Issue by TomInIreland** [iTwin/appui#350]
**Is your feature request related to a problem? Please describe.**
Our developers are using the new version of iTwinUI developing application UI.
They found out that the property, tree and prompt components doesn’t have close button by default.
after talking to our developer and Jon, i think AppUI widget doesn't close button so users connot close them.

**Describe the solution you'd like**
A button on to close AppUI widget.

**Additional image**
the text in the image is from stakeholder and it translate as "there's no X button to close these!"
![image001](https://github.com/iTwin/appui/assets/5287890/c0c62e74-531c-49c3-a21d-1e9ff639fd80)

**Comment by raplemie** [comment]
Hi @TomInIreland, we will look into adding this feature in the future, but might require opt-in since the developpers will need to provide a way to bring back the widgets if it gets closed.
