### ISSUE TITLE
Prepare moving from core-react to itwinui-react `Dialog`

### ISSUE THREAD

**Issue by AntanasBuk** [iTwin/appui#357]
Deprecate core-react `Dialog` component and all wrapper components like `ModelessDialog` and `GlobalDialog` (might need to identify more) that use it as a base. This is in favor of moving to using itwinui-react `Dialog` component that is in line with iTwinUI standards.
Use a temporary solution - `SimpleDialog` component - to replace base of other components that were using core-react `Dialog` as a base.

**Comment by AntanasBuk** [comment]
Deprecations in https://github.com/iTwin/appui/pull/366

**Comment by AntanasBuk** [comment]
Turns out there is also a `Dialog` component in appui-layout-react so not sure what to do with that one...

**Comment by AntanasBuk** [comment]
Edit: SimpleDialog was removed. In exchange, Dialog was modified to contain both iTwinUI Dialog and core-react Dialog features (without breaking changes). This does not change the fact that the Dialog will need to be deprecated when iTwinUI Dialog is fixed (in v3 hopefully).

**Comment by GerardasB** [comment]
Duplicate of https://github.com/iTwin/appui/issues/363
