### ISSUE TITLE
badgeType prop of toolbar items not working

### ISSUE THREAD

**Issue by jason-crow** [iTwin/appui#361]
**badgeType prop of GroupItemDef or its items not working** (also seems broken for other toolbar items)

**To Reproduce**

1. Create a UiItemProvider with provideToolbarItems
2. Have that provideToolbarItems return a GroupItemDef
3. set the GroupItemDef's (or its item defs') badgeType prop to BadgeType.TechnicalPreview (should now show the yellow preview badge)
4. Notice no badge shows

**Expected behavior**
Expect to see the yellow badge icon on the toolbar button (or its items if that was specified)

**Screenshots**
![image](https://github.com/iTwin/appui/assets/25822334/3a691f2b-71b4-4251-833f-a41f9da15105)
^^ despite having items configured like so:
![image](https://github.com/iTwin/appui/assets/25822334/57a9e3ef-5a82-4186-8420-abe335a62b09)
https://bentleycs.visualstudio.com/beconnect/_git/TCDEAppService?path=/packages/modules/design-review-common/src/modules/app-modules/backstage/BackstageUiItemsProvider.ts&version=GBmaster&_a=contents
![image](https://github.com/iTwin/appui/assets/25822334/92fc1e94-1aab-42dc-a0cd-8b6b831ec828)
https://bentleycs.visualstudio.com/beconnect/_git/TCDEAppService?path=/packages/modules/design-review-common/src/modules/app-modules/backstage/BackstageToolbarButton.tsx&version=GBmaster&_a=contents

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser: chrome
- Version:  114.0.5735.110
- iTwin.js AppUI Version: 4.0.1
- iTwin.js Version: 3.7.5 / 4.0.0 (doesn't matter)

**Comment by raplemie** [comment]
Hi, a fix for this have been included in 4.2.0, let us know if this address your issue!
