### ISSUE TITLE
Changed models visibility gets overriden initialViewState on ViewportComponent mount

### ISSUE THREAD

**Issue by GintV** [iTwin/appui#371]
**Describe the bug**

This is a regression comparing to iModel.js 2.19.x . We are using a viewportRef function property to get a reference to the ScreenViewport

![image](https://github.com/iTwin/appui/assets/17436829/0c755740-a883-45ab-aaeb-eba7ee7ba003)

After we do that, we adjust model visibility (add or remove models) by calling screenViewport.changeModelDisplay. After viewer is loaded, the adjustments we made are not present.

Looks like it happens because `screenViewportRef.current?.changeView(initialViewState)` is called one more time after line 279 was executed

![image](https://github.com/iTwin/appui/assets/17436829/2d6dbaee-493e-4d15-b905-4a56bfd5a1c3)

**Expected behavior**
After viewportRef function is called, view shouldn't be changed anymore on ViewportComponent mount.

**Desktop (please complete the applicable information):**

- OS: win 10
- Browser: chrome
- Version: 98.0.4758.141
- iTwin.js AppUI Version: 3.7.6
- iTwin.js Version: 3.7.6

**Comment by raplemie** [comment]
Thanks, we'll look into this and get back to you if I need more information.

**Comment by NancyMcCallB** [comment]
This code was added to properly process the async method. It's not as simple as removing the additional call. I will look at this more next week.

**Comment by raplemie** [comment]
Hi @GintV, a fix for this was released today in AppUI 4.6.4. Let us know if it fixes your issue!

**Comment by GintV** [comment]
@raplemie Seems to be fixed on 4.6.4, thanks!
