### ISSUE TITLE
Allow using a react svg component as an icon for action button when writing UiItemsProvider

### ISSUE THREAD

**Issue by YashodipD** [iTwin/appui#404]
I am frustrated because ToolbarItemUtilities.createActionButton() does not accept react icon from @itwin/itwinui-icons-react. 

I would like to see `createActionButton: (id: string, itemPriority: number, icon: string | ConditionalStringValue, label: string | ConditionalStringValue, execute: () => void, overrides?: Partial<ActionButton>) => ActionButton;`  is accepting icon in react SVG format which comes from @itwin/itwinui-icons-react.

Apart from above solution I don't have any alternatives in my mind.

Previously we used to create toolbar buttons with following code - 
`const clearGeometriesButton = ToolbarHelper.createToolbarItemFromItemDef(
        1004,
        new CommandItemDef({
          commandId: "Remove Geometries",
          iconSpec: <SvgDisconnect color="red" />,
          label: "Clear Geometries",
          execute: () => {
            GeometryManager.clearGeometries();
          },
        })
      );` 
As you can see iconSpec is directly accepting SVG icon. similar behavior I would like to see in `createActionButton ` function.

**Comment by raplemie** [comment]
Hi, can you try using appui-react version of the `ToolbarItemUtilities.createActionItem` instead, it should allow you to do what you need. Let us know if that works well or not.
