### ISSUE TITLE
Customizable tree node height

### ISSUE THREAD

**Issue by JoanaSmit** [iTwin/appui#405]
The tree node height is too small for mobile devices.
Make node height customizable so we could increase touch area.
![tree](https://github.com/iTwin/appui/assets/29892049/6b5ec16d-e01a-4b7a-b78c-7592b4aaa32e)

**Comment by saskliutas** [comment]
Hi, you can customize node height already. You can achieve that by passing custom `treeRenderer`: 

```tsx
<ControlledTree
  {...}
  treeRenderer={(treeProps) => <TreeRenderer {...treeProps} nodeHeight={() => 100} />}
 />
```

**Comment by JoanaSmit** [comment]
I copied the issue to iTwin/viewer-components-react because I need customizable node height in ModelsTree and CategoryTree.
