### ISSUE TITLE
PropertyGrid and Tree might become blank when switching widgets

### ISSUE THREAD

**Issue by saskliutas** [iTwin/appui#406]
VirtuallizedPropertyGrid and ControlledTree might become blank when switching widgets. This happens when PropertyGrid/Tree is scrolled to the bottom, other widget is opened and then widget containing PropertyGrid/Tree is opened again.

This issue is encountered because when switching widgets components inside aren't unmouted. As both PropertyGrid and Tree uses virtualized list we end up in a situation where list is scrolled to the bottom but scroll returns to the top after opening widget again without scroll event. Need to update virtualized list scroll position in this case.

**Comment by raplemie** [comment]
Fix for this was included in 4.3.0.
