### ISSUE TITLE
Change ThemeManagerProps "theme" property to string literals with predefined options

### ISSUE THREAD

**Issue by DenisMicha** [iTwin/appui#409]
Currently, ThemeManagerProps "theme" property is set to type string:
![image](https://github.com/iTwin/appui/assets/139454656/21f32cbf-722b-40c0-ab81-5b2a94706d73)

It should be changed to string literals with predefined options instead to avoid possible errors (due to typos like "liht" instead of "light", etc.). For example, there is a type ThemeType, which includes all the possible options:
![image](https://github.com/iTwin/appui/assets/139454656/c38e693e-8759-45ea-8aa5-87005a2270e3)

- iTwin.js AppUI Version 4.2.0
- iTwin.js Version 4.0.2

**Comment by raplemie** [comment]
The reason for this being a string is that the theme manager allows for custom theme provided by applications, so a full set of colors could be provided for `html[data-theme="customdark-theme"]` and the `<ThemeManager theme="customdark">...` would enable this.

The `ThemeType` is the `iTwinUI` which do not allow such customization.

**Comment by mayank99** [comment]
to keep support for a predefined string union (for autocomplete) and also support arbitrary strings (for custom themes), this is an option:
```js
theme: 'light' | 'dark' | 'os' | (string & {});
```

**Comment by raplemie** [comment]
Hi @DenisMicha, the typing for theme have been updated to properly provide the IDE autocomplete for themes. "random" string will still pass, but at least it should help. Let us know if this adresses your issue.

**Comment by DenisMicha** [comment]
> Hi @DenisMicha, the typing for theme have been updated to properly provide the IDE autocomplete for themes. "random" string will still pass, but at least it should help. Let us know if this adresses your issue.

@raplemie Hello, yes, looks good to me, thank you.
