### ISSUE TITLE
Fix "@itwin/no-internal-barrel-imports" linting errors

### ISSUE THREAD

**Issue by anmolshres98** [iTwin/appui#413]
**Describe the bug**

Because of [this PR I created](https://github.com/iTwin/appui/pull/401), there has been introduced a new linting error, specifically `@itwin/no-internal-barrel-imports : Do not consume barrel imports within the same package`. I have set the rule to "warn" for now in this base config file [here](https://github.com/iTwin/appui/pull/401#discussion_r1260243922) so that the PR can be merged. This "warn` value should be removed and the linting errors should be fixed instead.

**To Reproduce**

1. Go to base of repo
2. Run `rush lint`
3. See all the linting problems reported as warning
4. Remove the line with ` "@itwin/no-internal-barrel-imports": "warn",` in `ui/eslint.config.base.js`
5. Fix all the linting errors

**Expected behavior**
No linting problems reported when running `rush lint`

**Screenshots**
Example run of `rush lint`:
![image](https://github.com/iTwin/appui/assets/98850418/73d1d557-0c03-42df-a8e2-cb75c08be18c)

**Comment by aruniverse** [comment]
hey, just looking at the error now. 
looks like all the errors are coming from tests, and using the barrel should be ok
just suppress them in the config for all test files

**Comment by anmolshres98** [comment]
> hey, just looking at the error now. looks like all the errors are coming from tests, and using the barrel should be ok just suppress them in the config for all test files

Gotcha, `warn` or set it `off` entirely?

**Comment by aruniverse** [comment]
off; the rule is inapplicable here
go review the rule, can find it in the eslint plugin repo
