### ISSUE TITLE
Selection Changed events are not fired for Blank Connection

### ISSUE THREAD

**Issue by afraj-attar** [iTwin/appui#416]
**Describe the bug**
I am trying to add the Viewer Content Tools(hide, isolate, emphasize) for Viewer with Blank Connection. This can be used on the View Decorators as well as on iModel elements. On selection it displays the UI buttons. But in case of blank connection this event listener is not added.
![image](https://github.com/iTwin/appui/assets/84125955/cc055e1c-c5fe-4a7e-a392-88b023b3fcd3)

![image](https://github.com/iTwin/appui/assets/84125955/56c6f911-bee9-4400-9ae9-fd67e2022fbe)
![image](https://github.com/iTwin/appui/assets/84125955/d003dca9-f85d-402f-bbc5-175876692259)

**Expected behavior**
The SelectionSetChanged event should get fired even for Blank Connections.

**Comment by raplemie** [comment]
Hi @afraj-attar, a fix for this have been created and released in 4.4.0, let us know if that resolves your issue!
