### ISSUE TITLE
Internal API Usage

### ISSUE THREAD

**Issue by bsy-nicholasw** [iTwin/appui#419]
I was told to bring this up in a separate issue from here: https://github.com/iTwin/itwinjs-backlog/issues/782

Civil-iTwin has been examining usage of iTwin APIs marked internal, either getting such APIs promoted or refactoring to use replacements. We have the following usage from AppUI that needs guidance or promotion. You can find the Civil-iTwin team/project in our internal azure devops if you want to look at the code more closely the warnings below were emitted for.

**civil-frontend**
  - DialogManagerBase.getDialogZIndexDefault() internal or recommend better API.
    - src\components\InputEntryMessageBox.tsx(40,24): warning @itwin/no-internal : class "DialogManagerBase" is internal. 
    - src\components\DeleteConfirmationMessageBox.tsx(45,24): warning @itwin/no-internal : class "DialogManagerBase" is internal.
  - src\components\TreeNodeWithChildrenRenderer.tsx(47,26): warning @itwin/no-internal : property "TreeNodeRendererProps.onLabelRendered" is internal.
  - src\components\TreeNodeWithChildrenRenderer.tsx(149,22): warning @itwin/no-internal : enum "TreeComponentTestId" is internal.
  - src\components\TreeNodeWithChildrenRenderer.tsx(185,20): warning @itwin/no-internal : class "ImageRenderer" is internal.

**civil-reviewtools-frontend**
  - src\components\reportManager\TreeNodeEditorSizable.tsx(43,27): warning @itwin/no-internal : property "TreeNodeEditorProps.ignoreEditorBlur" is internal.

**Multiple Packages**
  - useLayoutResizeObserver, useRefState from "@itwin/core-react" are still internal. Examples:
    - src\Civil-iTwin\typescript\core\civil-frontend\src\components\VisibleComponent.tsx(21,27): warning @itwin/no-internal : function "useLayoutResizeObserver" is internal.  
    - src\Civil-iTwin\typescript\core\civil-frontend\src\components\VisibleComponent.tsx(20,32): warning @itwin/no-internal : function "useRefState" is internal.

@a-gagnon @simnorm

**Comment by GerardasB** [comment]
> * DialogManagerBase.getDialogZIndexDefault() internal or recommend better API.

What is the use case? Could you use one of our provided dialog components instead? Alternatively, we have a `--uicore-z-index-dialog` CSS variable.

> * src\components\TreeNodeWithChildrenRenderer.tsx(47,26): warning @itwin/no-internal : property "TreeNodeRendererProps.onLabelRendered" is internal.

@saskliutas 

> * src\components\TreeNodeWithChildrenRenderer.tsx(149,22): warning @itwin/no-internal : enum "TreeComponentTestId" is internal.

This is used for testing strictly, why do you need this?

> * src\components\TreeNodeWithChildrenRenderer.tsx(185,20): warning @itwin/no-internal : class "ImageRenderer" is internal.

Use newly exported `TreeNodeIcon` instead https://github.com/iTwin/appui/releases/tag/release%2F4.2.0


> * src\components\reportManager\TreeNodeEditorSizable.tsx(43,27): warning @itwin/no-internal : property "TreeNodeEditorProps.ignoreEditorBlur" is internal.

@saskliutas


>   * src\Civil-iTwin\typescript\core\civil-frontend\src\components\VisibleComponent.tsx(21,27): warning @itwin/no-internal : function "useLayoutResizeObserver" is internal.

Use one of 3rd party packages instead i.e. https://www.npmjs.com/package/use-resize-observer https://www.npmjs.com/package/@react-hook/resize-observer

>   * src\Civil-iTwin\typescript\core\civil-frontend\src\components\VisibleComponent.tsx(20,32): warning @itwin/no-internal : function "useRefState" is internal.

Use `React.useState` hook instead.

**Comment by saskliutas** [comment]
> > * src\components\TreeNodeWithChildrenRenderer.tsx(47,26): warning @itwin/no-internal : property "TreeNodeRendererProps.onLabelRendered" is internal.
> 
> @saskliutas

 I think this should be promoted to `public` I will open PR for this.

> > * src\components\reportManager\TreeNodeEditorSizable.tsx(43,27): warning @itwin/no-internal : property "TreeNodeEditorProps.ignoreEditorBlur" is internal.
> 
> @saskliutas 

This is not used and maybe should be removed. I see that you just copied `TreeNodeEditor` code and made some modifications. You can just emit `ignoreEditorBlur` property.

**Comment by bsy-nicholasw** [comment]
> > DialogManagerBase.getDialogZIndexDefault() internal or recommend better API.
> What is the use case? Could you use one of our provided dialog components instead? Alternatively, we have a --uicore-z- 
> index-dialog CSS variable.

We have a few custom dialogs, I think they were just mimicking example code from AppUi. Having this in CSS is probably a better way to go @simnorm @Maxime-Brassard @a-gagnon 

> > * src\components\TreeNodeWithChildrenRenderer.tsx(149,22): warning @itwin/no-internal : enum "TreeComponentTestId" is internal.
> 
> This is used for testing strictly, why do you need this?

I'm not sure, I guess it was used for debugging/testing on our end too. Sounds like it can be omitted.

**Comment by bsy-nicholasw** [comment]
I think we're all set, closing this issue
