### ISSUE TITLE
Option for ToolbarComposer not to bring in addon items

### ISSUE THREAD

**Issue by bsy-nicholasw** [iTwin/appui#424]
The pop-up action toolbar in measure-tools-react was recently refactored and uses the ToolbarComposer. There's a regression with the old functionality where we get non-measurement items appearing in the popup.

I see the [ToolbarComposer ](https://github.com/iTwin/appui/blob/ff744cc48a55051ccf482481c20cc0c40b232ede/ui/appui-react/src/appui-react/toolbar/ToolbarComposer.tsx#L291C40-L291C62) queries for more items from UI providers, can we get an option to not do this and have our toolbar remain "private"?

For reference, the usage in measure-tools is in [PopupToolbar](https://github.com/iTwin/viewer-components-react/blob/master/packages/itwin/measure-tools/src/widgets/PopupToolbar.tsx) and used [here](https://github.com/iTwin/viewer-components-react/blob/080f31089da1c6b4b45915fc0b6383d43ef9f965/packages/itwin/measure-tools/src/widgets/MeasurementActionToolbar.tsx#L436).

**Comment by raplemie** [comment]
@bsy-nicholasw The goal of the `ToolComposer` is to actually fill a `ToolbarWithOverflow` with `UiItemsProvider` provided tool items, so adding a feature to remove its main purpose would not be a good move forward, however, as #314 is asking, there is currently an issue with the `ToolbarWithOverflow` that prevents proper use of the `Conditional` type of elements provided. I will move the handling to the proper level which should address this issue as well.

**Comment by raplemie** [comment]
Hi @bsy-nicholasw, as mentioned above, `Toolbar` component now correctly handle the `Conditional` type and should give you the results needed, it also now have a `enableOverflow` prop that will have the same behavior than `ToolbarWithOverflow`, making this single component the goto for any toolbars. Let me know if this address your issue!
