### ISSUE TITLE
ContextSubMenu's right icon looks huge

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/appui#426]
`ContextSubMenu`'s `SvgCaretRight` icon looks huge compared to before.

4.2.0 version of AppUI:
![image](https://github.com/iTwin/appui/assets/129863171/546bedc0-844e-451d-80e7-ee58710a6916)

How it looked in 3.7.x version:
![image](https://github.com/iTwin/appui/assets/129863171/247a3dc0-709a-490d-bb85-42c917dc79c5)

It is possible that it looked alright in 4.1.0 version but I do not have screenshots from that time to check.

**Comment by raplemie** [comment]
Hi, we'll look into this! Thanks for the report!

**Comment by raplemie** [comment]
Hi @AAugustBentley, a fix for this was provided in 4.4.0 which was released today, let us know if the result is correct!
