### ISSUE TITLE
Remove NineZone term from iTwinjs 4.x public docs and property descriptions

### ISSUE THREAD

**Issue by YashodipD** [iTwin/appui#428]
When I was reading about ToolbarUsage. I came across Ninezone term. It is very confusing if you are new developer and looking at it. NineZone UI pattern is used very long back in iTwinjs 2.x

Please remove / hide all the Ninezone related details in iTwinjs 4.x docs / property description.

Take a look at - https://www.itwinjs.org/reference/appui-react/toolbar/toolbarusage/

**Comment by raplemie** [comment]
Documentation site was just updated to fix this!
