### ISSUE TITLE
Tree nodes are not aligned properly

### ISSUE THREAD

**Issue by saskliutas** [iTwin/appui#439]
Tree nodes in same hierarchy level without expander has different offset than the ones that have expander. 

Actual:
![image](https://github.com/iTwin/appui/assets/24278440/89506cb8-f89c-4dc1-92c4-022c7f5dde6a)

Expected:
![image](https://github.com/iTwin/appui/assets/24278440/98e6f1af-324b-4fed-adc3-44503cd24e4b)

**Comment by raplemie** [comment]
Thanks, we'll look into it!

**Comment by raplemie** [comment]
Hi @saskliutas, a fix for this was released today in 4.5.0. Please give it a try and let us know if it fixes the issue!

**Comment by grigasp** [comment]
> Hi @saskliutas, a fix for this was released today in 4.5.0. Please give it a try and let us know if it fixes the issue!

I can confirm the nodes are aligned fine now. Thanks.
