### ISSUE TITLE
ToolSettings - Empty tool settings message is not changing based on tool selection

### ISSUE THREAD

**Issue by Emi1yZhang** [iTwin/appui#442]
**To reproduce the issue:** 
1. Open any iModel.
2. Switch to any other frontstage and then switch back to the main one.
3. Select a tool that doesn't have any tool settings - distance measurement for example.
4. Notice that empty tool settings message doesn't pick up correct active tool in label and still shows the first one that was selected on iModel open, so in this case it'll always be "Select Elements" tools.
![image](https://github.com/iTwin/appui/assets/129224356/6b2a4a46-5842-4e2e-91df-e01af16d7867)

**Possible fix:** 
[appui/ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx at master · iTwin/appui · GitHub](https://github.com/iTwin/appui/blob/master/ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx)
Add a callback based on activeToolId to change emptySettings correspondingly to this function.
<img width="281" alt="image" src="https://github.com/iTwin/appui/assets/129224356/c133c049-e61d-4732-837e-c6c5916158d8">

Thank you!

**Comment by raplemie** [comment]
Thanksk for reporting this, we'll look into it!

**Comment by raplemie** [comment]
Hi @Emi1yZhang, a fix for this was released today in 4.5.0, please give it a try and let us know if it fixes your issue!
