### ISSUE TITLE
UI: Unpinned panel handle starts to flicker on hover and fails to open the panel

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#443]
#### Environment

- __Package version(s)__: 4.3.0
- __Operating System__: Windows 11
- __Browser name and version__: Google Chrome 115.0.5790.110 and Firefox 115.0.2

#### Steps to reproduce

1. Unpin any of the panels
1. Make sure that it's closed and you see the panel handle
1. Move your mouse to the end of the window, near the panel handle

#### Actual behavior

Notice that unpinned panel handle starts to flicker on mouse hover and fails to open the panel

#### Expected behavior

In the case of unpinned and collapsed panel, it should just always open on hover

#### Additional information

Quick demo of the issue from Pineapple side:

![93d16df8-65ec-4cbf-afbb-05288ae8dc92](https://github.com/iTwin/appui/assets/1904889/6581ce1a-d385-400a-a9c3-85f404946b54)

**Comment by joehenry9498** [comment]
Have not been able to reproduce this on the standalone. No flickering and panels open without issue. Seems like will need to be tested with pineapple

**Comment by joehenry9498** [comment]
We were unable to reproduce this issue on our side with the standalone, connected, and sandbox applications. Looked into pineapple source code as well, issue was reproducible but no AppUI fix could be determined. Do you have a specific time period or version you started noticing this issue? @vermanas

**Comment by vermanas** [comment]
@joehenry9498 Initially this was noticed on 5/5/2023 and during that time Pineapple was using 4.0.0 version of AppUI.

**Comment by vermanas** [comment]
@joehenry9498, @raplemie we investigated it a little bit more in Pineapple and this is only reproducible when panel collapse setting is set to automatic. If it's "On Click" - flickering effect is not noticeable. 

Also, make sure that the unpinned widget is near the border of the furthest monitor, if you're on multi-monitor setup.

**Comment by raplemie** [comment]
Hi @vermanas, a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!

**Comment by raplemie** [comment]
Ok, as I cant reproduce, let me know when 4.6.0 is deployed somewhere that I can test it, I'll investigate further.

**Comment by vermanas** [comment]
@raplemie, @wilmaier I can't seem to reproduce it anymore with AppUI 4.6.0. Looks like it's working fairly good, so I think we can treat this as solved.
