### ISSUE TITLE
Measure tools action toolbar needs new ToolbarUsage type

### ISSUE THREAD

**Issue by wilmaier** [iTwin/appui#445]
Currently, the measurement actions toolbar is also populated with the frontstages group because the ToolbarUsage type ContentManipulation is too general pupose.

To solve this, it would be helpful to have a new ToolbarUsage type like 'Measurements'.

![MicrosoftTeams-image (2)](https://github.com/iTwin/appui/assets/48260215/dc96fbc8-a40e-4e43-af35-ee0af8dccc36)

**Comment by raplemie** [comment]
AppUI is only providing 2 ToolbarUsage as we only deliver 2 toolbar widget, where would those Measurements go ?

**Comment by wilmaier** [comment]
The toolbar shown is the measurement right-click action toolbar.  This is implemented in MeasurementActionToolbar.tsx of viewer-components-react in the measure-tools package.
