### ISSUE TITLE
Codemod: Support 4.4.0 ToolWithOverflow upgrade

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#446]
**Is your feature request related to a problem? Please describe.**
Next version (tentatively 4.4.0) move uses of `<ToolbarWithOverflow overflowExpandTo={Direction} ... />` to `<Toolbar enableOverflow={{overflowExpandTo:Direction}} ... />`, change that could be automated with codemod

**Describe the solution you'd like**
Running `codemod 4.4.0` should handle these changes

**Describe alternatives you've considered**
Manual changes

**Additional context**

Codemod tool already exists and could be improved.

once this is implemented, deprecate `ToolbarWithOverflow` component

**Comment by GerardasB** [comment]
Let's avoid the maintenance burden for now.
