### ISSUE TITLE
Ability to get information about specific widget container

### ISSUE THREAD

**Issue by DenisMicha** [iTwin/appui#450]
There is a need to set the state of a specific widget (open/closed/etc.) on element selection based on whether the widget is alone in its container or not, but currently it is not possible to get that information to check the condition.

For that on element selection it should be possible to get information about what is the container/container Id for a specific widget, and about what widgets that container contains/number of widgets in that container, or to check the condition mentioned above in any other way if possible.

**Comment by raplemie** [comment]
As a widget can typically be dragged to any panel/floating panel, what is the usecase where this condition would not be confusing to the user ?

**Comment by raplemie** [comment]
You would get this exact behavior by simply always setting the widget state to "Closed" whenever the widget is not already "Open":
If the panel is empty (so hidden), the panel will show with your widget open, as it will be the only widget in the panel, (be it side or floating)
If the panel is visible but the widget is hidden, it will show the tab, but not set it active.

**Comment by DenisMicha** [comment]
Do you mean just
```if (widget.state !== Open) {
widget.setState(Closed)
}```
on element selection?
If so, it does not work in my case:

- The default state is set to Hidden and it should remain hidden when no element is selected, but with this condition, if it is on a side panel it is visible as Open with no data since there is no selected element, and if it is floating, the tab is visible but Closed (so this widget is not being set to Open just because it is the only widget in a container)
- If floating, the widget always becomes visible but Closed when selecting an element, only opens when clicked on that widget and then closes again when selecting another element/clearing selection

**Comment by GerardasB** [comment]
Looking for a valid use case. Closing this issue for now.
I'd advise using a combination of `useWidget` to figure out if the widget is `docked` vs `popout` vs `floating`(and its state i.e. whether it's hidden or not) and something like media queries or `useWidgetDirection` to figure out the appropriate widget content layout.
