### ISSUE TITLE
Dropdown closes when UI auto-hides in Tool Settings when widget is docked

### ISSUE THREAD

**Issue by AAugustBentley** [iTwin/appui#461]
When tool settings are docked, clicking on a dropdown shows its choices but they disappear after a short while when the UI auto hides. The dropdown works just fine when tool settings are undocked/in a pop-up.

![image](https://github.com/iTwin/appui/assets/129863171/baa492b4-7589-476a-81d9-a1739d12e10d)

To create the dropdown, we send DialogItem with enum.choices in the property object.

![image](https://github.com/iTwin/appui/assets/129863171/050a9b9b-95c0-481e-9b15-eedab661dcbe)

**Comment by raplemie** [comment]
Hi @AAugustBentley, I was not able to reproduce this behavior in our test app, is it possible that there is a timed event in your tool that would refresh the tool settings ? If that's the case, the container would be re rendered and the open state of the select would be lost, causing this behavior.

**Comment by AAugustBentley** [comment]
The strange part is that undocked it works just fine. I do not think we have timed events, we update values only on changes.

**Comment by AAugustBentley** [comment]
I checked but it seems when docked, there are some timers and hide ui in `InternalUiShowHideManager.ts` which triggers some breakpoints without doing anything.
![image](https://github.com/iTwin/appui/assets/129863171/bdd30bb4-a6da-4079-9e91-a4cc7805601c)

**Comment by raplemie** [comment]
Ok, I confirm that I can reproduce this, and it is indeed when the Ui auto hides after a timeout that this happens, we'll look into it!

**Comment by AAugustBentley** [comment]
Hello, @raplemie, is there any update for this item?

**Comment by raplemie** [comment]
Yes, there is a PR open and linked to this issue.

**Comment by AAugustBentley** [comment]
We need this fix for our release. Is there an estimation of when PR could be completed and a new version with the fix released? Thanks

**Comment by raplemie** [comment]
I think we should be done with this tomorrow, I'd like to include #499 as well in the next release if possible by the end of the week.

**Comment by raplemie** [comment]
Hi @AAugustBentley, a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!

**Comment by AAugustBentley** [comment]
@raplemie, looks like this fix solved the problem. thank you
