### ISSUE TITLE
missing details in docs - AccuDrawshortcut 

### ISSUE THREAD

**Issue by YashodipD** [iTwin/appui#464]
I found out we cannot show AccuDrawKeyboardShortcuts without passing an instance of FrameworkToolAdmin to toolAdmin prop of viewer. It is not mentioned anywhere in the docs.

Add note at the end of this page - https://www.itwinjs.org/reference/appui-react/accudraw/accudrawkeyboardshortcuts/

Add more details related to this in the description of - https://www.npmjs.com/package/@itwin/web-viewer-react

**Comment by raplemie** [comment]
Thanks for the report, we'll look into this!

**Comment by raplemie** [comment]
Hi @YashodipD, I updated the documentation and the page now have links to the relevant documentation, which should give the proper information that the `FrameworkToolAdmin` is required and where it should be used. That should give information for web-viewer as well, as the user should start from `AccuDrawKeyboardShortcuts` regardless. Let us know if that seems correct!

**Comment by YashodipD** [comment]
In `ui/appui-react/src/appui-react/tools/FrameworkToolAdmin.ts` this file , we mentioned about setting focus to Home. I did not see anywhere written how do we do it. I know we do it using `esc` however how will newcomer/outsider will know about it. 
![image](https://github.com/iTwin/appui/assets/113993668/b86b7181-2244-4d58-b222-e8aae81c49fc)

**Comment by raplemie** [comment]
`setFocusToHome` is a method on `UiFramework.keyboardShortcuts`, which is linked there, I think that should be enough.

**Comment by YashodipD** [comment]
Nevermind... After looking at code, I just realized, `Esc` key specific to AccuDraw which sets focus to home. Earlier I thought `Esc ` is a global shortcut.

**Comment by YashodipD** [comment]
Looking good, Thank you!
