### ISSUE TITLE
Technical Preview Badge does not work as toolbar override

### ISSUE THREAD

**Issue by afraj-attar** [iTwin/appui#466]
**Describe the bug**
I am trying to add a technical preview badge to an existing tool item. This worked in appui-react 3.x but does not work in 4.4.0.

**To Reproduce**

1. Create a toolbar item using ToolbarHelper.createToolbarItemFromItemDef function.
2. Pass in badgeType as BadgeType.TechnicalPreview in overrides parameter.
![image](https://github.com/iTwin/appui/assets/84125955/76ed8de9-96b7-4eb4-b9e9-4b2fe0b6c826)
3. The badge type is not applied.
![image](https://github.com/iTwin/appui/assets/84125955/38b906a0-ee5f-4927-8e0c-a2edcca8e0a4)

**Expected behavior**
On AppUI 3.x, the preview badge used to appear correctly.
![image](https://github.com/iTwin/appui/assets/84125955/9660a73f-3129-4c74-bc9c-f0f38ff775fc)

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser - Chrome
- iTwin.js AppUI Version - 4.4.0
- iTwin.js Version - 4.1.1

**Comment by raplemie** [comment]
Hi @afraj-attar, a fix for this was relased today in 4.5.0. Please try it out and let us know if it fixes the issue!
