### ISSUE TITLE
Tool Settings widget - can't set to no docking allowed

### ISSUE THREAD

**Issue by wilmaier** [iTwin/appui#470]
**Describe the bug**
The setter does not allow setting to an empty array.  No restrictions are applied if undefined.

  public set allowedPanelTargets(
    targets: ReadonlyArray<StagePanelLocation> | undefined
  ) {
    this._allowedPanelTargets =
      targets && targets?.length > 0 ? targets : undefined;
  }

**Comment by raplemie** [comment]
Hi @wilmaier, a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!
