### ISSUE TITLE
mention in docs that we cannot send notifications to users, until status bar is enabled.

### ISSUE THREAD

**Issue by YashodipD** [iTwin/appui#471]
Lack of information in docs, it would be helpful if you could mention that enable status bar to send user notifications.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Notifications-and-Messages---iTwin.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.itwinjs.org/learning/ui/appui-react/notifications/

**Comment by raplemie** [comment]
Hi @YashodipD, I did not change the documentation but rather the unexpected behavior that the `StatusBar` was required to display the notification messages. This has been updated in 4.7.0 which was relased last Friday, let me know if this address your issue!

**Comment by YashodipD** [comment]
Now I clearly understand that there is no dependency between status bar and notifications. If that is correct, I have fine with changes. thank you!
