### ISSUE TITLE
Hidden widget uses default tab location after opening then closing temp frontstage

### ISSUE THREAD

**Issue by jason-crow** [iTwin/appui#480]
The tab location of a hidden widget is lost when opening then closing a nested frontstage. Upon being shown next it will appear in the default tab location (top left panel)

**To Reproduce**

1. Go to https://qa-review-uks.itwin.bentley.com/context/8b3d0653-02b5-4a76-832e-7c16ed50ff21/imodel/b9bf7a2d-bf2e-4d3f-b127-90c8029a855e?it3Mode&changesetid=308791f67a9c5ece81a1c792b3ab3cf1ab584b47
2. Select an element, notice the Property Grid appears in the bottom right panel 
3. Clear element selection
4. Open an issue from the Issues widget
![image](https://github.com/iTwin/appui/assets/25822334/11f05110-b2bb-40cc-914c-99ece45897a8)
5. Open a Markup Stage from the Notes tab
![image](https://github.com/iTwin/appui/assets/25822334/75483e42-52bf-4137-aa1d-c89d72cd060b)
6. Close the stage
7.  Select an element, notice the Property Grid appears at the top left

**Expected behavior**
The Property Grid should continue to show in the bottom right panel

**Screenshots**
Expected: 
![image](https://github.com/iTwin/appui/assets/25822334/55f835a0-8669-499d-ba19-738a9fae292c)
Observed:
![image](https://github.com/iTwin/appui/assets/25822334/ff9f635c-2b59-4b2c-9a0d-d29e2a84b0b5)

**Desktop (please complete the applicable information):**

- OS: Windows
- Browser: Chrome
- iTwin.js AppUI Version: 4.4.0 (also reproducible in 4.3.1)
- iTwin.js Version: 4.1.0

- Seems to require a Nested Frontstage to be open then closed
- Pineapple's Work Item: https://dev.azure.com/bentleycs/beconnect/_workitems/edit/1275024

**Comment by raplemie** [comment]
Hi @jason-crow, a fix for this was published today in 4.5.1, please test it out and let us know if this address the issue correctly!
