### ISSUE TITLE
MessageCenterField layout issue when message is too long

### ISSUE THREAD

**Issue by DaumantasJankauskas** [iTwin/appui#485]
**Describe the bug**
When MessageCenterField tries to display a long enough message it's layout breaks.

**Screenshots**
Before:
![image](https://github.com/iTwin/appui/assets/47949861/babc8a7d-6f23-4c2b-8c77-4cb0abed7585)

After:
![image](https://github.com/iTwin/appui/assets/47949861/4076e0d4-2397-40f8-a5e9-7567d5725485)

**Comment by raplemie** [comment]
Thanks, we`ll look into this.

**Comment by raplemie** [comment]
Hi @DaumantasJankauskas, a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!
