### ISSUE TITLE
Dialog position need percentages and bottom right positioning

### ISSUE THREAD

**Issue by RaphaelVanierBentley** [iTwin/appui#486]
**Problem and Limitation**
Right now, the Dialog Position can only be set by 2 variables: **X and Y: Initial top right position of dialog in px.**

This is limiting since we might want some dialogs to doc near the bottom or the right of the screen. We have the possibiliity to calculate where is the bottom or the right right now, but if we enlarge the browser window, the dialog will stay where it is and now follow the bottom of the screen.

Also, a set amount of pixels means that the dialog will never move even if the browser window change size.

**Ideal Solution**

Instead of X and Y, we could have Top, Bottom, Left and Right like CSS. And like width and height they could be of type string | number , this would allow percentages and pixels (Ex: "50%", "50px" or 50)

**Other alternatives**

A few work arounds I have considered right now

- Make the window movable so the user can redock it at the bottom if the Dialog get lost in the center.
- Calculate percentage manually with ScreenVieport on Dialog creation.

**Context**

Exemple of smaller screen where it fits right at the bottom of the screen:

![image](https://github.com/iTwin/appui/assets/124394026/c52e03cc-e9cf-4d10-af6c-86cb1625563f)

But when we enlarge the viewport, it get lost in the center of the screen:

![image](https://github.com/iTwin/appui/assets/124394026/3f127786-9ceb-4966-8f28-8a462fd4f0d7)

**Comment by raplemie** [comment]
Hi, this can be acheived with the current system by providing a css class to your dialog and overriding the default positionning (which becomes permanent if you dont set the dialog to `movable`)

Here is an example of this: https://www.itwinjs.org/sandboxes/RaphaelLemieux/positionned-dialog

Let me know if this helps.
