### ISSUE TITLE
MessageCenterField message icon has no colour based on severity

### ISSUE THREAD

**Issue by DaumantasJankauskas** [iTwin/appui#488]
**Describe the bug**
Messages in MessageCenter have no colouring on their icons.

As far as I know, message icons were coloured based on severity back in Appui 3.x. 

**Expected behavior**
Icons have colours based on severity.

**Screenshots**
Current: 
![image](https://github.com/iTwin/appui/assets/47949861/b8df5f07-4475-45c7-8210-530137b1302c)

Expected: 
![image](https://github.com/iTwin/appui/assets/47949861/8f97d855-68d6-482d-b9d3-fdb073d8d663)

**Comment by raplemie** [comment]
Thanks, we'll look into this!

**Comment by raplemie** [comment]
Hi @DaumantasJankauskas , a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!
