### ISSUE TITLE
Full stack tests failure on mac os

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/appui#490]
**Describe the bug**
Running full-stack-tests/ui playwright tests fail on M1 Mac / Ventura 13.2.1. 

**To Reproduce**
1.`rush build`
2.`cd full-stack-tests/ui`
3.`rushx test`

**Expected behavior**
Tests should produce the same result across platforms.

**Screenshots**
<img width="1148" alt="image" src="https://github.com/iTwin/appui/assets/78756012/1eb3aef6-83d4-4c57-9789-9508734ba08b">
**Desktop (please complete the applicable information):**

- OS: M1 Mac / Ventura 13.2.1. 
- iTwin.js AppUI Version 4.6.0-dev.0
- iTwin.js Version 3.7.0 (dev deps)

**Comment by raplemie** [comment]
Hi @ben-polinsky, I dont have access to a Mac and the pipelines are running on MacOS, none of the tests are indeed expected to be different on different OS, Not sure how we would go about this.

**Comment by ben-polinsky** [comment]
>  I dont have access to a Mac 

Which is why I've self-assigned it :)

It also looks like you are not running these tests on a mac in CI?

https://github.com/iTwin/appui/blob/a6164991e307fb86d24be19021014018cdfaf206/common/config/azure-pipelines/templates/core-build.yaml#L81

**Comment by raplemie** [comment]
Right, we dont run `rush test` but `rush cover` on all OS (which do not include fullstack, my bad.

**Comment by ben-polinsky** [comment]
All good! We'll see when I have time to get to this :)

**Comment by ben-polinsky** [comment]
Passes on external monitor. Fails on internal macbook monitor.

**Comment by GerardasB** [comment]
We are running these in a docker environment, which should help with flakiness.
