### ISSUE TITLE
Widget setting "canFloat: { isResizable: false }" not doing anything 

### ISSUE THREAD

**Issue by Juliakas** [iTwin/appui#497]
**Describe the bug**
When configuring widget and setting `canFloat: { isResizable: false }` nothing happens.

**To Reproduce**

1. Go to https://itwin.github.io/appui/495/?path=/docs/widget-canfloat-options--docs
1. Change setting `isResizable` to "False"
1. Move widget around (don't dock it)
1. Resize widget

**Expected behavior**
When configuring widget and setting `canFloat: { isResizable: false }` widget should not be resizable. 

**Screenshots**

**Desktop (please complete the applicable information):**

- OS: Windows 11
- Browser: Edge
- Version: 117
- iTwin.js AppUI Version: 4.5.0 (but reproducible in storybook)
- iTwin.js Version 4.1.6

**Comment by raplemie** [comment]
Hi @Juliakas, a fix for this have been released in 4.6.0 released today, let us know if this fixes your issue!

**Comment by Juliakas** [comment]
The issue has been resolved - we are not able to resize widgets when appropriate setting is set. Thanks for fixing this :)
