### ISSUE TITLE
Ghost widgets keep mounting on each widget popout

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#498]
#### Environment

- __Package version(s)__: Core 4.0.3, AppUI 4.3.0
- __Operating System__: Windows 11
- __Browser name and version__: electron 24.1.2

#### Steps to reproduce

1. Open frontstage with a widget that can popout
2. Popout widget
3. Close popped-out widget

#### Actual behavior

After each popout, a new widget instance is mounted and never unmounted

#### Expected behavior

Either no new widget instance is mounted on popout OR if it is mounted, it should be unmounted once widget popout is closed

**Comment by raplemie** [comment]
@GintV Recreated issue, I left out the video in case there was internal only information, feel free to add it back if it is public safe.

**Comment by joehenry9498** [comment]
Hey @GintV, I'm working on this issue now. If the video is not public safe can you send it to me over teams so that I have some more info to work off of?

**Comment by raplemie** [comment]
Hi @GintV, a fix for this was released in 4.6.2, the popout will still remount in the popout, but will unmount when the popout is closed, let us know if this fixes your issue! The behavior should improve further when we tackle #524, but that should remove the lingering widget.
