### ISSUE TITLE
Widgets state is not persisted after switching frontstage

### ISSUE THREAD

**Issue by DenisMicha** [iTwin/appui#506]
Widget state is not persisted after switching frontstage.

Steps to reproduce the behaviour:

1. Go to any frontstage
2. Select any element
3. Change state (dock/undock, location) of any widget that appears after selecting an element
4. Go to another frontstage (right after the previous step, without clearing selection)
5. Go back to the initial frontstage
6. Select any element again
7. See that the widget with previously changed state is back to the state it had **before** the state was changed (it was not persisted)

**Expected behaviour**
Widget with previously changed state is in the same state and location where it was left before leaving the initial frontstage.

- iTwin.js AppUI Version 4.5.1
- iTwin.js Core Version 4.1.6

**Comment by raplemie** [comment]
Hi, thanks for reporting this, I'll have a look at this next week, sorry for the delay.

**Comment by raplemie** [comment]
Hi, I cannot reproduce this with the example widget we have currently in 4.6.2. 

https://github.com/iTwin/appui/assets/1904889/e1832b40-e7ad-48e2-ae94-f1c56e5867fb

Can you validate if the issue persists on your side ?

**Comment by DenisMicha** [comment]
> Hi, I cannot reproduce this with the example widget we have currently in 4.6.2.
> 
>  FrontstageSwitch.mp4 
> Can you validate if the issue persists on your side ?

Hi @raplemie, we also cannot reproduce it anymore with 4.6.1, so it seems this is resolved. Thanks!

**Comment by raplemie** [comment]
Awesome, thanks!
