### ISSUE TITLE
HTMLElement does not work with ReactNotifyMessageDetails

### ISSUE THREAD

**Issue by Alfonso-Martello** [iTwin/appui#519]
**Describe the bug**
`ReactNotifyMessageDetails` accepts `MessageType = string | HTMLElement | ReactMessage` as valid types for its `detailedMessage` prop. However, an error occurs when attempting to output a HTMLElement as a message using `ReactNotifyMessageDetails` with `MessageManager.outputMessage`.

**To Reproduce**

This sandbox reproduces the behavior:
[ReactNotifyMessageDetails-does-not-support-html](https://www.itwinjs.org/sandboxes/AlfonsoMartello/ReactNotifyMessageDetails-does-not-support-html).
Please go to this sandbox and follow the instructions in the widget.

**Current behavior**
Error is thrown:
`Objects are not valid as a React child (found: https://imjsdocumentprodeussa01.z13.web.core.windows.net/sandbox/compiler/index.html?lng=en&itwinid=402f1a92-c7b1-4012-b787-7fa45e2e7fe4&imodelid=b55dec38-d9b7-4029-9b9c-6b899151328f#). If you meant to render a collection of children, use an array instead.`

**Expected behavior**
HTMLElement should be displayed in toast.

**Comment by raplemie** [comment]
Hi, I'm currently working in this area, I'll check what's going on.

**Comment by raplemie** [comment]
Hi @Alfonso-Martello, a fix for this was released today in 4.7.0. Let us know if this fixes your issue!
