### ISSUE TITLE
Do not close open widget after docking (drag&drop) into Panel

### ISSUE THREAD

**Issue by 1abjora** [iTwin/appui#553]
**Is your feature request related to a problem? Please describe.**
1. Open a widget in any Panel.
2. Have prepared another Panel with at least one widget.
3. Now grab an open widget from step 1 and drag&drop into the Panel in step 2
4. Observe the widget gets closed.

**Describe the solution you'd like**
The widget should retain open state (WidgetState.Open) the same time closing previously open Widget on the recipient Panel. 

**Describe alternatives you've considered**
A) if an open widget was drag&dropped in the same Panel (start and finish of an open widget is the same Panel) it should remain open (now it gets closed)
B) A setting to turn off (control) the new behavior.

**Additional context**

**Comment by raplemie** [comment]
Hi @1abjora, on top of the requirements stated above, would you expect the widget to open if it was closed in the origin panel?

**Comment by 1abjora** [comment]
I suggest to open it. Rationale behind it - you touch a widget means you open it:

  1.  Have prepared several widgets in the same panel.
  2.  Mouse down on closed widget;
  3.  Mouse move - options:
     *   none
     *   side move a bit that a widget drag starts but do not leave the same panel
     *   full move to another panel
  4.  Release mouse and see the widget gets opened.

________________________________
