### ISSUE TITLE
Widget.show() in popout should do *something*

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/appui#564]
**Is your feature request related to a problem? Please describe.**
For civil, whenever we update what is currently displayed in a widget, we make sure it stands out by calling the following:
```ts
  widget.setWidgetState(WidgetState.Open);
  widget.show();
```
This is a common workflow for sections. We have a tool that uses the main 3d view to position the cross section somewhere in the model, and the change is reflected in the cross section view (hosted in a widget).

The snippet above ensures that if the widget is docked and it's not the active tab, then it becomes the active tab. That gives **some level** of indication to the user that something's changed and they should pay attention.

**Describe the solution you'd like**
We need to have something similar for when the widget is in popout. I don't really mind if it's a 'bring to front' mechanism or that the browser window blinks in the windows taskbar -- as long as there's **something** to catch the user's attention.

**Comment by raplemie** [comment]
If we gave a target name to the popout window, and simply recalled "open" on that same window, chrome (need to test with other browsers) would bring back the existing window to the front (but not move or resize it), would that be sufficient ?



https://github.com/iTwin/appui/assets/1904889/9aef43cb-4972-4d2c-910c-e4c84258cf86
