### ISSUE TITLE
Unit test failures on mac os

### ISSUE THREAD

**Issue by ben-polinsky** [iTwin/appui#575]
There are unit test failures on mac os:

```
1) WidgetContent
       should render:
     Error: Assert: Programmer Error
```

```
1) MenuTab
       should render:
     Error: Assert: Programmer Error
```
     
<img width="1108" alt="image" src="https://github.com/iTwin/appui/assets/78756012/afddcf7e-b790-4648-ba16-f438f11c7360">

**Comment by GerardasB** [comment]
We moved to `vitest`, there are still some timing issues in our tests, but doesn't seem platform specific.
