### ISSUE TITLE
TimelineComponent totalDuration and initialDuration update bug

### ISSUE THREAD

**Issue by DovileVirbalaite** [iTwin/appui#611]
**Describe the bug**
In TimelineComponent changing totalDuration and initialDuration props results in incorrect fraction returned in onChange callback.
It seems like initialDuration update is made before the totalDuration update which is why onChange fraction is incorrectly calculated with the previous totalDuration value.

**To Reproduce**
Trying to change speed in timeline (fast – 10000, medium – 20000, slow – 60000):
1. set totalDuration and initialDuration to same value 20000
2. update totalDuration and initialDuration values to 10000 (change speed to fast)
3. onChange callback returns incorrect fraction: 0.5
4. timeline UI duration is jumping in random places when continue changing speed

**Expected behavior**
It is expected to get correct fraction when initialDuration and totalDuration is updated, in this example to get fraction as 1 when totalDuration and initialDuration is updated to the same value (timeline duration should stay at the end) .

**Screenshots**
In this example only totalDuration and initialDuration values are being updated, printing them in console with onChange fraction value: 
![image](https://github.com/iTwin/appui/assets/88542754/5f397339-9aa8-4df9-acf6-16a549ec4f49)
![image](https://github.com/iTwin/appui/assets/88542754/1b0e87c3-87cb-49fc-8239-78ea9575c85c)

**Desktop:**

- OS: iOS, Android
- Browser: chrome, safari
- iTwin.js AppUI Version: 4.5.1
- iTwin.js Version 4.1.7

**Comment by raplemie** [comment]
Hi @DovileVirbalaite, a fix for this was released today in 4.7.0. Let us know if this fixes your issue!

**Comment by DovileVirbalaite** [comment]
Hi @raplemie, this fix partially fixes the issue, but there are more problems with TimelineComponent.

There is still the case when incorrect fraction is returned onChange callback. I can reproduce it with these steps:

1. play timeline and move it to the middle
2. change speed to slow, then change speed to fast while timeline is still playing
3. some race condition happens when updating the state and incorrect fraction is returned, which makes timeline to stop and show incorrect time.

This reproduces everytime on Android (chrome) and sometimes on iOS(safari). Seems like in `TimelineComponent.tsx `function `_setDuration` is called both from `_updateAnimation` and `componentDidUpdate` and fraction gets calculated incorrectly because of some race condition. This is weird since I believe it should be running on a single thread. I'm adding the printed logs where the problem occurs and where I'm printing them in your code (I copied your TimelineComponent code locally for debugging).

<img width="587" alt="Screenshot 2024-01-10 at 10 04 30" src="https://github.com/iTwin/appui/assets/88542754/07a4e771-edf5-4967-baff-b8ae5d30a454">

<img width="441" alt="Screenshot 2024-01-08 at 12 55 24" src="https://github.com/iTwin/appui/assets/88542754/ace03030-daab-46e9-882b-33d90c917f29">

**Comment by DovileVirbalaite** [comment]
Hi @raplemie, are there any updates about this issue?
