### ISSUE TITLE
Widget with `ThemeProvider` cannot pop content outside of floating widget

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#612]
With popout rendering change, or with iTwinUI 3.0 content, widgets that uses popouts (Select component for example) now need to include a ThemeProvider within the body of their widget, however, when doing so, the popout is rendered "within" the widget when it is floating, and the poped out content is no longer expanding beyond the widget.

It would be nice to:
* Not have to include `ThemeProvider` for widgets that are using AppUI provided iTwinUI version.
  We initialy thought of providing directly, but because of the overflow issue, we decided to not do it.
* If a `ThemeProvider` is used, the popout would be rendered as if there was none
  Initial investigation shows that `.nz-widget-widget` class is responsible for the `overflow: hidden` rule, we need to investigate if this is required.

Visual of the issue.
No provider: 
<img width="824" alt="image" src="https://github.com/iTwin/appui/assets/1904889/10033528-e0e9-4478-8ea4-0a4de1c8233b">

With provider:
<img width="903" alt="image" src="https://github.com/iTwin/appui/assets/1904889/4f5bdbd5-25ba-4a95-a4fa-4a7882f02c17">

**Comment by GerardasB** [comment]
This doesn't seem to be an issue with iTwinUI 3.0, because a [portalContainer](https://github.com/iTwin/iTwinUI/pull/1477) can control where the floating elements are appended.
