### ISSUE TITLE
Error when creating a custom TreeImageLoader that returns svg source type.

### ISSUE THREAD

**Issue by AnDuong249** [iTwin/appui#657]
**Describe the bug**
In the components-react package, when using a custom TreeImageLoader that returns the svg sourceType like below for the ControlledTree, this would give me an error relating to Buffer and the image would not be loaded.

**To Reproduce**

1. Create a custom TreeImageLoader that returns a svg sourceType such as below.
```
class CustomSvgImageLoader implements TreeImageLoader {
  /** Loads image data from either [[TreeNodeItem]] */
  public load(_item: TreeNodeItem): LoadedImage | undefined {
    const warningSVG = `<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem"><path d="M15.868 13.267l-6.77-11.62a1.15 1.15 0 00-1.1-.67 1.17 1.17 0 00-1.1.69l-6.77 11.59a1.2 1.2 0 001.1 1.72h13.45a1.237 1.237 0 001.306-1.06 1.19 1.19 0 00-.116-.65zm-6.87-.29h-2v-2h2zm0-3h-2v-5h2z" fill="var(--iui-color-icon-warning, hsl(33 90% 33%))"/></svg>`;

    return {
      sourceType: "svg",
      value: warningSVG,
    };
  }
}

const customImageLoader = new CustomSvgImageLoader();
```

2. Pass this imageLoader into the TreeNodeRenderer of ControlledTree
```
<TreeNodeRenderer
        {...treeNodeProps}
        imageLoader={customImageLoader}
        className={className}
      />
```
3. See error when the tree is being rendered.

**Screenshots**
![image](https://github.com/iTwin/appui/assets/116378951/35411898-ac17-4554-8602-a0bf6e28f46d)

**Desktop (please complete the applicable information):**

- OS: Windows 11 23H2
- Browser:  Chrome 120.0.6099.110
- iTwin.js AppUI Version: 4.8.0
- iTwin.js Version: 4.3.2

**Additional context**
Using core-icon sourceType gives no errors for me.
```
class CustomSvgImageLoader implements TreeImageLoader {
  /** Loads image data from either [[TreeNodeItem]] */
  public load(_item: TreeNodeItem): LoadedImage | undefined {
    return {
      sourceType: "core-icon",
      value: "icon-status-warning",
    };
  }
}
```

**Comment by GerardasB** [comment]
Fixed in 4.8.3 https://github.com/iTwin/appui/releases/tag/release%2F4.8.3
