### ISSUE TITLE
core-react UnderlinedButton is not styled properly in toast notification

### ISSUE THREAD

**Issue by a-gagnon** [iTwin/appui#680]
**Describe the bug**
We're displaying a React component that uses `<UnderlinedButton/>` through ReactNotifyMessageDetails. As shown in the image below, it's displayed properly when it lies in the message center, but not when showing up as a toast notification.

**To Reproduce**

1. Create a simple react component with a `<UnderlinedButton/>` from the core-react package.
2. Create a `ReactNotifyMessageDetails` and pass the reactNode defined in 1.
3. Call `MessageManager.outputMessage`

**Expected behavior**
Style should be consistent.

**Screenshots**
![image](https://github.com/iTwin/appui/assets/3418768/167c3f4d-9c2f-45f0-be22-5020c3dc4a6e)

**Desktop (please complete the applicable information):**

- Browser: Chrome
- Version: 120.0.6099.217 (Official Build) (64-bit) (cohort: Stable) 
- iTwin.js AppUI Version: 4.6.3
- iTwin.js Version: 4.6.0

**Comment by raplemie** [comment]
Thanks, we'll look into this!

**Comment by joehenry9498** [comment]
Hi @a-gagnon, I wasn't able to reproduce this with the listed steps. The result is below. Can you send more information of your ReactNotifyMessageDetails so that I can try to mirror the styling of your toast?
![Screenshot 2024-01-19 090930](https://github.com/iTwin/appui/assets/70602409/91275b41-0d70-4e6e-916e-2915ae4c43e2)
![Screenshot 2024-01-19 090946](https://github.com/iTwin/appui/assets/70602409/1e2c970b-507b-4898-a1b5-0c11e289b04a)

**Comment by a-gagnon** [comment]
Looks like something is overriding --buic-foreground-primary for some reason.
I'll keep digging on my side, but here's the DOM for both cases:

![image](https://github.com/iTwin/appui/assets/3418768/343a40dd-12d1-4dd8-898f-2f3d75cd461b)

![image](https://github.com/iTwin/appui/assets/3418768/b23a28e5-be62-453d-b0c2-4df1b8efa682)

**Comment by joehenry9498** [comment]
Hey @a-gagnon, another thing you could also try is using the 'Anchor' component for iTwinUI. The goal in the future is to get away from core-react so this would help facilitate that. If you use the Anchor component and add as="button" the styling mirrors the UnderlinedButton, except the underline only appears when you hover over (This may be able to be changed as well if you prefer the underline to stay). https://itwinui.bentley.com/docs/anchor
![Screenshot 2024-01-22 130352](https://github.com/iTwin/appui/assets/70602409/d0b02edd-a5b0-44d4-bcc9-2392fddf567c)
![Screenshot 2024-01-22 130122](https://github.com/iTwin/appui/assets/70602409/1c06f13c-bcc0-499a-b07d-ac02dbc88f14)

**Comment by a-gagnon** [comment]
Thanks @joehenry9498 I tried the Anchor as you suggested and it has consistent styling across the board. I'll replace all our usage of UnderlinedButton with it.
