### ISSUE TITLE
Can't fix a widget location in the viewer

### ISSUE THREAD

**Issue by Lionel-Lim** [iTwin/appui#691]
Hi there.

I am trying to fix the widget location but `StagePanelLocation` is not working even if I set it left or right.
For example,
The code below set the widget panel location to Right.
However, the widget keeps using the last location that a user changed.
```
if (
            stageUsage === StageUsage.General && location === StagePanelLocation.Right && section === StagePanelSection.End
        ) {
            const helloWidget: Widget = {
                id: 'HelloWidget',
                label: 'Hello',
                defaultState: WidgetState.Open,
                content: <CustomWidget />,
                allowedPanels: [ StagePanelLocation.Right ],
            };
```

How to make the widget forget the last location and always uses the pre-assigned location only?

Best
DY

**Comment by GerardasB** [comment]
Hey @Lionel-Lim, at the moment we do not have the capability to reset a specific widget in the layout.

You can restore the whole layout of a frontstage by calling [`restoreLayout()`](https://www.itwinjs.org/reference/appui-react/frontstage/frontstagedef#restorelayout) or specifying a [`version`](https://www.itwinjs.org/reference/appui-react/frontstage/frontstageconfig/version/) property:
https://github.com/iTwin/appui/blob/2fad12bb0922ebc67a2fadd5283dd82892a45d56/test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/TestFrontstageProvider.tsx#L56
https://github.com/iTwin/appui/blob/2fad12bb0922ebc67a2fadd5283dd82892a45d56/test-apps/appui-test-app/appui-test-providers/src/ui/widgets/LayoutWidget.tsx#L357
Would this solution work for your use case?

**Comment by Lionel-Lim** [comment]
Hi, @GerardasB.

It is sad to hear that resetting a specific widget is not supported yet. However, `restoreLayout()` more or less solved my issue. Thank you.
