### ISSUE TITLE
Widgets with shared state between different frontstages

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#70]
There is a need to share widget state between different frontstages.
It could also be handled from the app side, but certain APIs should be available, i.e. to move Widget to a different panel.

DR workflow:
1. **Issues widget** is opened in **main frontstage**
2. **Issues frontstage** is opened (**issues widget** might render in a different panel)

**Comment by raplemie** [comment]
Frontstages are intended to be "user workflows", so people would likely want to have different configuration depending on what they are working on. 

To reach a similar behavior, an application could use conditionals widget state and stay in a single frontstage.

Forcing some widgets to be in a specific place and others to not change place would get weird state in "which one" is the active for a particular panel when switching.

We'll close this for now until we have further evidence of usefulness.
