### ISSUE TITLE
Add status bar option to handle split views

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/appui#715]
**Is your feature request related to a problem? Please describe.**
Users want a consistent way to manage split views.

**Describe the solution you'd like**
Introduce a button in the status bar that opens a popover to allow the user to split the view.  Will likely require some additional thinking.  Mockups are dated and may not match current visual styling.
![Screenshot 2024-02-01 at 10 17 21 AM](https://github.com/iTwin/appui/assets/849817/6d273eb4-03aa-4e03-929d-9dd3be5fd48e)

**Comment by GerardasB** [comment]
Discussions are ongoing, we'll determine how it should work in the future.
