### ISSUE TITLE
Maintenance: cSpell cleanup

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#720]
**Is your feature request related to a problem? Please describe.**
Currently, the code base is scattered with cSpell ignores.

**Describe the solution you'd like**
Remove cSpell ignores from source files.
Clean up `cSpell.json` and make sure it's the only place where ignores are added.
Consider enabling `cspell` for CI builds.

**Comment by MBudreviciusBentley** [comment]
Still need to add it to CI builds
