### ISSUE TITLE
Review "ToolAssistanceFiled" tests, which contain leaks

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#74]
While refactoring the ToolAssistanceFiled test to use react-testing-library, I found that after the indicator is clicked and there is actually an instructions to display, the mocha will report that the tests is leaking and node keeps running.

The control is quite complex so I will need to go back and investigate.

```
  it.only("clicking the button having instructions will cause leaks", async () => {
    render(<StatusBar widgetControl={widgetControl} />);
    await theUserTo.click(screen.getByRole("button"));

    const notifications = new AppNotificationManager();
    const mainInstruction = ToolAssistance.createInstruction(ToolAssistanceImage.CursorClick, "Click on something", true);
    const instructions = ToolAssistance.createInstructions(mainInstruction);
    notifications.setToolAssistance(instructions);

    expect(true).to.be.true;
  });

```

**Comment by GerardasB** [comment]
Closing this, since we moved to `vitest` https://github.com/iTwin/appui/pull/790
