### ISSUE TITLE
Active viewport border is not visible

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#785]
### Describe the bug

When there are multiple viewport, a brown bar usually appear at the top of the active viewport to indicate that it is active. In our case, it works well in our widgets since we use `FloatingViewportContent`. However, we no longer see the brown bar in the main view.

After some investigation, it turns out that the bar is there, but it is hidden behind the docked tool settings.

Note that pinning the top panel causes the bar to appear as expected.

### To Reproduce

Have multiple views in a frontstage
Have docked tool settings displayed
Notice that the top bar is not visible.

### Expected Behavior

The top bar should always be visible when the view is active, regardless of tool settings and pinned top panel state.

### Screenshots

https://github.com/iTwin/appui/assets/1904889/a1d5851b-bb4e-40ae-956e-19fe29268b8f

### Desktop (please complete the applicable information)

AppUI 4.10.0

### Additional context

This issue was likely introduced by #577, or #705, sorry.
We are not using any of the preview features yet.

**Comment by ignas-k** [comment]
Fixed in #793.
