### ISSUE TITLE
Use of cloneElement in EditorContainer

### ISSUE THREAD

**Issue by AdamMeza-Bentley** [iTwin/appui#788]
### Describe the bug

Not a bug per se, but use of `cloneElement` is advised against in the [React docs](https://react.dev/reference/react/cloneElement). It's currently being used in this way: 

Let's replace this with one of the suggested solutions!

### Screenshots

![Screenshot 2024-03-28 101055](https://github.com/iTwin/appui/assets/148785417/7281fb5c-24b8-4cca-8624-c2948802f402)

### Desktop (please complete the applicable information)

N/A

**Comment by GerardasB** [comment]
Existing editor components will be deprecated in the future, no proactive maintenance is planned for now.
