### ISSUE TITLE
Remove dependency on `@bentley/icons-generic`

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#798]
### Describe the Solution you'd like

Remove the dependency on deprecated `@bentley/icons-generic` package. Replace SVGs with components from `@itwin/itwinui-icons`. If there's no replacement - inline the icon.

**Comment by FlyersPh9** [comment]
Whoever picks this up can work with me on deciding what icon to replace with.

**Comment by GerardasB** [comment]
This can be done in a follow-up minor version instead of blocking the major version release.
