### ISSUE TITLE
Create a toolbar using iTwinUI components

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/appui#80]
Create a toolbar in AppUi based on the iTwinUi ButtonGroup component.

**Comment by FlyersPh9** [comment]
In [this CodeSandbox](https://codesandbox.io/s/appui-itwinui-5krcnc?file=/src/canvas.tsx:888-982) I applied a class that overrides the iTwinUI-React `<ButtonGroup>` (see `canvas.scss` & `canvas.tsx`).

If we want to avoid overriding styles, maybe a wrapper component might work.
```tsx
<AppUIToolbar>
    <ButtonGroup>
        <IconButton styleType="borderless">
            <SvgCursor />
        </IconButton>
    </ButtonGroup>
</AppUIToolbar>
```
`<AppUIToolbar>` could apply the frosted glass background effect, border to ensure visibility above any background color, & the opacity change based off cursor movement & proximity.  The buttons within would all be of `styleType="borderless"` so you'd see the frosted glass effect thru them.  If you only needed one button, you could exclude `<ButtonGroup>` as well.

One thing to be aware of is that the iTwinUI borderless button w/ dropdown will likely appear something like this:
![Screenshot 2023-05-05 at 3 19 54 PM](https://user-images.githubusercontent.com/849817/236550666-89173300-39b6-4d9d-9169-2be00cde8ef0.png)
We would want to keep our toolbar buttons aspect ratio 1:1, so we'd likely need to add some customization to replace the dropdown arrow with something more like this:
![Screenshot 2023-05-05 at 3 23 38 PM](https://user-images.githubusercontent.com/849817/236551326-de9bccdd-e4d6-487e-b024-0bceed12bebc.png)
