### ISSUE TITLE
Support truncating labels in ControlledTree

### ISSUE THREAD

**Issue by bsy-nicholasw** [iTwin/appui#805]
### Is your feature request related to a problem? Please describe.

This is coming from the Civil-iTwin team, we use the `ControlledTree` from the `components-react` package. We had a request to truncate the labels of the nodes in our usage of that component, which one of our developers has done - but it required the usage of `!important` because of the node-wrapper styling also using `!important`

![image](https://github.com/iTwin/appui/assets/84341979/10c27569-a42a-4b23-8cba-975f244f2d76)

The look and feel of what we're trying to achieve is this:

![image](https://github.com/iTwin/appui/assets/84341979/634a72c3-0657-442b-bc59-fa6b31083b08)
![image](https://github.com/iTwin/appui/assets/84341979/4c00ef7d-2f4e-4da5-a273-f83eb1c925a0)

### Describe the Solution you'd like

It would be great if the tree exposed an option to truncate labels out of the box.

**Comment by FlyersPh9** [comment]
If I had to guess why the tree rows are not truncated currently is so the user could view the full name.  If truncation was introduced, how would the user view the full name?  Hover + tooltip is often what I see suggested but hover isn't possible on touch devices and it becomes an accessibility issue.

**Comment by saskliutas** [comment]
We are no longer actively working on `ControlledTree` component. My suggestion for you would be to move to iTwinUI [`Tree`](https://itwinui.bentley.com/docs/tree) component. If that is not an option for you I think your workaround looks like a reasonable solution for this. You are also welcome to open PR and add this feature to `ControlledTree`.
