### ISSUE TITLE
UI: Create release notes and docs processing for appui packages.

### ISSUE THREAD

**Issue by NancyMcCallB** [iTwin/appui#83]
# Changelog - Always Per Package
- [x] Requirement - `changelog.md` must sit next to your package's package.json.
- [x] For Rush - `changelog.jsons` are generated, then on `rush version` they are combined to changelog.md
- [x] We link to this in the docs on a package's index page.
 
# Release Notes - Lockstep (one per repo) | Out of lockstep (one per package)
- [x] Requirement - In lockstep - Use next-version.md as previous. Release tags can be `release/{version}` as is currently the case.
- Requirement - if out of lockstep - store next-version.md for each package in {packageRoot}/changehistory/next-version.md. 
- [ ] Modify version-bump.yml (found in core repo) or your equivalent publish build accordingly:
    You will need to iterate through each package and:
    - Ensure your release tag is  `release/{packageName}@{version}`.

    On a new minor (and thus also on major) release:
    - [ ] Do the next version "dance"
      - Rename the nextVersion.md file to docs/changehistory/{version}
      - For repos with packages out of lockstep, this will need to be: packageRoot/changehistory/{tag} which will probably be something like docs/changehistory/packageName@version.md
    - [ ] bumps version / Creates a tag
    This triggers the new release below.

 
- [ ] Alter create-release.yml (Ben/Yash will provide an updated version of this file, including for completeness)
    - [x] In lockstep (no changes needed): grab the corresponding markdown file from docs/changehistory/{version}.md
    - [ ] Out of lockstep - grab the corresponding markdown file from {packageRoot}/changehistory/{tag}:
    - [ ] Modify python script to write this file into the github release instead of the current changelog notes.
- [ ] We link to the release from the docs package's index page.

**Comment by raplemie** [comment]
Updated the issue description with the provided steps.
