### ISSUE TITLE
imodel-components-react "button.label.settings" not being translated

### ISSUE THREAD

**Issue by EK723** [iTwin/appui#841]
### Describe the bug

In TimelineComponent.tsx, the button labelled "button.label.settings" is not localized. When the mouse hovers over the button, rather than showing the appropriate localized name, "button.label.settings" appears instead

### To Reproduce

1. Go to a timeline
2. Hover the mouse over the elipses button in the time scrubber
3. The tooltip does not give the localized name of the button

### Expected Behavior

The tooltip should give the localized name of the button

### Screenshots

![Bug](https://github.com/iTwin/appui/assets/163031993/30a42eee-79fd-437a-9609-02df9f8a554a)

### Desktop (please complete the applicable information)

- OS: Windows
- Browser: Firefox, Edge
- appui-react version: 4.12.0 
- iModel-Components-React Version: 4.12.0

**Comment by GerardasB** [comment]
Fixed in https://github.com/iTwin/appui/releases/tag/release%2F4.13.3
