### ISSUE TITLE
User's widget layout preferences not saved

### ISSUE THREAD

**Issue by maxime-lavergne** [iTwin/appui#842]
### Describe the bug

**Expected behavior**
Users have the ability to move widgets around to redefined their UI layout as they want. When a user leaves the viewer, he's expecting that his layout will be saved throughout his sessions with the viewer.

**Current behavior**
The user's layout isn't saved properly.

### To Reproduce

1. Checkout and run apps/test-viewer from https://github.com/iTwin/viewer-components-react with any model
2. Drag any widget to another section of any panel. (https://github.com/iTwin/appui/assets/147163568/7ef37697-bee5-4a4c-8579-d76ab6447d13)
3. Reload the page
4. Notice the widget layout is reset

** 2.5 - Reorder widgets within the same section. (https://github.com/iTwin/appui/assets/147163568/327a1b09-2036-41b2-8c3a-761b081a64e9)

### Expected Behavior

Dragging any widget to another section or reordering widgets tabs should be preserved throughout users' sessions.

### Screenshots

Initial load local storage key: 
![image](https://github.com/iTwin/appui/assets/147163568/31869a24-3896-4288-b24b-8ed5adfc4c58)

After the user has moved a widget to another section: 
![image](https://github.com/iTwin/appui/assets/147163568/2c585fc7-6cf0-47e3-8530-2d01eae1c675)

After reordering widget tabs: 
![image](https://github.com/iTwin/appui/assets/147163568/4230f540-f38e-4b64-9eec-6a266ee6aeed)

After reloading: 
![image](https://github.com/iTwin/appui/assets/147163568/2b26f672-8bf2-44b6-b709-43d0178ccd46)

### Desktop (please complete the applicable information)

Chrome Version 124.0.6367.119 (Official Build) (64-bit)

**Comment by miguelsoares1624** [comment]
Just to add that this was working fine in previous versions, users are already using this functionality and this will be now a big regression to them (issue with migration to v4). Please consider this as important

**Comment by GerardasB** [comment]
This is due to https://react.dev/blog/2022/03/29/react-v18#new-strict-mode-behaviors
I'll fix the affected hooks.

**Comment by GerardasB** [comment]
Fixed in https://github.com/iTwin/appui/releases/tag/release%2F4.13.4
