### ISSUE TITLE
Keyboard shorcuts are called 2 times. And Control key flag is ignored. 

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/appui#876]
### Describe the bug

Hi o/, 

## Issue 

I have a shortcut liked to a letter. `p`
Ex: 
![image](https://github.com/iTwin/appui/assets/82905333/173ba9be-1418-4244-a198-f50b555d84b1)

When I press `p`, the execute function is called 2 times. 
I expect it to be called only one time. 

An example of how this can be problematic.
In my case, the shortcut opens a Dialog, which gets opened 2 times, one on top of each other... 

## Debug + fix :

I tracked where `execute` is called from, one is in accudraw code and the other one in UIFramework code : 
![image](https://github.com/iTwin/appui/assets/82905333/e50f093d-21d0-436b-928b-e9d309fac306)

The accudraw code ignores all other checks. Ex : (`isCtrlKeyRequired`, `isFocusOnHome`).
So, when I do `ctrl + p`, my shortcut is called from there. It should be ignored, like the UIFramework codes do. 

I suggest to remove the whole accudraw `handleKeyDown` function and handle these shortcuts properly with the Framework. 

Thanks. (:

**Comment by GerardasB** [comment]
I can not reproduce the described behavior of a shortcut executing twice. I assume it's due to the fact that `keydown` event of input is only emitted when the input is focused, but then `isFocusOnHome` getter returns false in `FrameworkToolAdmin`.

**Comment by mathieu-fournier** [comment]
Realted to : https://github.com/iTwin/appui/issues/819
