### ISSUE TITLE
Need for new "Deprecation" BadgeType (simlar to TechPreview)

### ISSUE THREAD

**Issue by noelgonzalezjones** [iTwin/appui#877]
### Is your feature request related to a problem? Please describe.

We have a need to identify to users that some Features, Services and Products are in the process of being deprecated with a visual identifier.

### Describe the Solution you'd like

The proposed solution is to have a new BadgeType for "Deprecation" that will allow a corner icon to identify Features, Services and Products that are going through the deprecation process.

Example mock-up here: 
![image](https://github.com/iTwin/appui/assets/172519857/0b46deda-e270-4c06-9b9a-525e9e8041f7)

**Comment by FlyersPh9** [comment]
Attaching the SVG created by @VincentChabot1:
![deprecated-badge 1](https://github.com/iTwin/appui/assets/849817/b6367431-39b5-46c4-961d-b98f3005d14a)

**Comment by noelgonzalezjones** [comment]
Please can you clarify if the change would be to AppUI or iTwinUI? As Clas,h we can take the latest version of AppUI but we are limited to iTwin V2.8.0 (It is an OKR for Q3 to upgrade to the latest iTwinUI)

**Comment by ignas-k** [comment]
The change would be in AppUI.
