### ISSUE TITLE
Property Grid: Editing mode is not exited when data changes

### ISSUE THREAD

**Issue by saskliutas** [iTwin/appui#913]
### Describe the bug

When property editor is activated and property grid data changes (e.g. selected item changes) editing mode is not closed. In case data changes editor should be closed without trying to commit new value.

### To Reproduce

1. Open property grid and start editing any property.
2. Change property grid data.
3. Property editor is still open.

### Expected Behavior

Property editor should close when data changes

**Comment by grigasp** [comment]
The fix released with `@itwin/components-react@4.16.0`
