### ISSUE TITLE
Double onPropertyUpdated in PropertyGrid when pressing Tab

### ISSUE THREAD

**Issue by karolis-zukauskas** [iTwin/appui#932]
### Describe the bug

`PropertyGridComponent` from `@itwin/property-grid-react` calls `onPropertyUpdated` twice when you press TAB key (while editing a property). The two calls lead to some issues in our update implementation that uses `EditCommand`s - you cannot start two overlapping `EditCommand`s. This currently doesn't cause huge issues but our we end up showing this warning (when handling the second attempt to start `EditCommand`):
![image](https://github.com/user-attachments/assets/dc88b8eb-4d55-4fd7-bce5-d9daaed2af2b)

It also seems that `onPropertyUpdated` is called when focus is lost, this leads to some nasty error cycle if the first call throws and we want to show some kind of error alert UI - I'm guessing that error alert moves focus, `onPropertyUpdated` runs again, it errors out, we show an error alert again ...
![image](https://github.com/user-attachments/assets/4badf52f-dde4-45e6-af24-e01fcb812064)

NOTE:
There is a similar issue already: https://github.com/iTwin/appui/issues/915

### To Reproduce

1. Start editing a property
2. Press TAB
3. Notice that it is called twice - first call is not awaited when second one is done.

See sample code and resulting console logs:
![image](https://github.com/user-attachments/assets/27fb96d3-209a-4acf-9939-b52e002232a4)

### Desktop (please complete the applicable information)

Reproduced in iTwin Studio, here are its versions:

Version: 1.0.63 (b7a3432) 
Build: iTwin Desktop Platform (Mango) 2024.07.10-2 
iTwin.js: 4.7.4 
iTwinUI: 3.10.0 
AppUI: 4.12.0 
React: 17.0.2 
Node.js: 20.9.0 
Electron: 29.1.0

**Comment by grigasp** [comment]
The fix released with `@itwin/components-react@4.16.0`
