### ISSUE TITLE
Rounding error with numerical operators in PropertyFilterBuilder

### ISSUE THREAD

**Issue by morgankertz** [iTwin/appui#990]
### Describe the bug
**NOTE:** you can right click -> open link in new tab on the gifs to view them larger

We are consuming the PropertyFilterBuilder in Pineapple for use in the query builder. When using numerical operators (>, >=, <, <=, between, not between), there is a potential rounding issue where elements that should be returned from that query are not.

In the below example, I create a query with `width = 400mm` that highlights the shown element.
![Recording 2024-08-30 at 15 07 46](https://github.com/user-attachments/assets/e636b97e-7d65-4412-af1e-88f2976c5288)

 If I change that query to `width <= 400mm`, the element that was highlighted before is no longer highlighted. 
![Recording 2024-08-30 at 15 11 05](https://github.com/user-attachments/assets/4fda898b-14f8-49df-a62d-a83ee44b75c9)

If I change that query once again to `width <= 401mm`, that element with width 400mm is being highlighted again.
![Recording 2024-08-30 at 15 12 07](https://github.com/user-attachments/assets/bfd5b5d6-a1fe-4d07-ada8-2b59a2c56555)

We're seeing similar issues with >= and the between operator as well.

### To Reproduce

1. Go to [this model](https://qa-review-uks.itwin.bentley.com/context/a4f3737d-d35b-42b6-ae9a-993847de9da3/imodel/7b109a51-1ea6-4dc1-ae45-ce28a74c2791?frontstage=ClashDetectionV2Frontstage&manifest=eyJpbmNsdWRlIjpbImJhY2tzdGFnZSIsImNsYXNoQWRtaW5pc3RyYXRvciIsImNsYXNoVmFsaWRhdGlvbiIsImdyb3VwcyJdLCJleGNsdWRlIjpbXX0%3D) 
2. Click "Create" in the Clash frontstage
3. Click "Manage" in the Groups tab
4. Select this element
    
    ![image](https://github.com/user-attachments/assets/70d912c0-2103-49a4-88f0-5f83f74f8660)
5. Right click the width property in the properties widget
6. Click "Add to Query" in the context menu
7. Click the paint palette icon in the header to execute/visualize the query
8. Change the operator from "Equal" to <=
9. Type in 400
10. Verify selected element not being highlighted
11. Change 400 to 401
12. Verify selected element is now being highlighted

### Expected Behavior

If the selected element's width property is 400, then `width <= 400` should return that element.

### Desktop (please complete the applicable information)

- Windows 11
- Chrome Version 127.0.6533.120 
- AppUI: 4.16.2
- iTwin.js - 4.8.5

**Comment by morgankertz** [comment]
@saskliutas upon further discussion, it would be ideal especially for the `<=`, `>=`, and `between` operators if we could use the distinct values selector with single selection rather than manually entering the value.

Since it seems like even copying the exact text of the display value in the property grid and entering it as the property value in the rule doesn't yield the same raw value, the easiest course would be to allow the user to select the exact property value like we do for the `Equal` operator but narrow it to a single selection.

Would this be something you would be open to supporting?

**Comment by morganadrales** [comment]
@grigasp so if I'm understanding correctly - you would make the necessary changes to determine the precision needed by the formatter and cascade those changes through the `GenericInstanceFilter ` for us to use? That approach theoretically should work for us, then we can build the buffer like you specified:

for `WHERE x >= {raw_value}`, we'd instead use `WHERE x >= {raw_value} - {roundoff_error} - {epsilon}`.
for `WHERE x <= {raw_value}`, we'd instead use `WHERE x < {raw_value} + {roundoff_error} + {epsilon}`.

**Comment by grigasp** [comment]
> @grigasp so if I'm understanding correctly - you would make the necessary changes to determine the precision needed by the formatter and cascade those changes through the `GenericInstanceFilter ` for us to use?

Yes, that would be my suggestion. @saskliutas, how feasible would it be to get that done for next week's 4.9 release?

**Comment by saskliutas** [comment]
I think we should make it into 4.9. It looks like only changes required in itwinjs-core is to extended some types to allow storing rounding error alongside numeric value

**Comment by morganadrales** [comment]
@saskliutas @grigasp that sounds great, thank you!

**Comment by grigasp** [comment]
@morgankertz, the following changes have been released:
-  iTwin.js Core version `4.9` contains the required type definition additions (https://github.com/iTwin/itwinjs-core/pull/7161).
- `@itwin/presentation-components` version `5.5` contains editor changes to set the `roundingError` attribute.

After consuming both of the above, you should start getting `roundingError` next to rule values in `GenericInstanceFilter`.
